"""
Alpha-Bio rich component catalog (iter-205, Feb 2026)

Expands the thin per-platform 12-component template from
`alpha_bio_brochure_data._COMMON_COMPONENTS_BY_PLATFORM` into per-subtype rows
(one entry per visible variant) so each system tile in the Implant Database
shows the same depth as Neodent / Nobel / MIS LANCE+.

Source: Alpha-Bio Brochure (job artifact `AlphaBio Brochure .pdf`).
Per-subtype rows extracted from brochure section "Prosthetics by Connection"
(CS / CHC / IH platforms) and the dedicated NeO and Multi NEO sections.

The data shape matches the existing `Component` schema used by the catalog
editor (`type`, `subtype`, `platform`, `gingival_heights_mm`, `angulations_deg`,
`material`, `retention`, `torque_ncm`, `catalog_code`, `indication`, etc.).
"""

from typing import Dict, List


# ── Component palettes per platform ────────────────────────────────────────
#
# Each list mirrors the brochure ordering (cover screw → healing → straight →
# angled → MUA → ti-base → scan-body → impression coping → analog → screws →
# temp → casting → ALPHALOC → ball → pre-milled → burnout sleeve).

_CS_COMPONENTS: List[Dict] = [
    # Cover screws
    {"type": "cover_screw", "subtype": "Cover Screw SF-N",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SF-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing"},
    {"type": "cover_screw", "subtype": "Cover Screw (Black-Coated) SFT-N",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SFT-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing — colour-coded"},

    # Healing abutments — Ø 4.0 / Ø 4.9 / Ø 6.2 mm × cuff heights
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø4.0 mm",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [1.5, 2.5, 3.5, 4.5, 5.5],
     "torque_ncm": 10, "catalog_code": "HA-D4-CH*-CS",
     "indication": "Narrow emergence profile"},
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø4.9 mm",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.9, "gingival_heights_mm": [1.5, 2.5, 3.5, 4.5, 5.5],
     "torque_ncm": 10, "catalog_code": "HA-D4.9-CH*-CS",
     "indication": "Standard emergence profile"},
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø6.2 mm",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.2, "gingival_heights_mm": [1.5, 2.5],
     "torque_ncm": 10, "catalog_code": "HA-D6.2-CH*-CS",
     "indication": "Wide emergence profile"},

    # Straight final abutments
    {"type": "final_abutment", "subtype": "Straight Titanium Abutment TLA-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.5, 2.5, 3.5, 4.5], "diameter_mm": 4.8,
     "torque_ncm": 30, "catalog_code": "3501",
     "indication": "Single-tooth cement-retained restoration"},

    # Angled final abutments
    {"type": "final_abutment", "subtype": "Angled Abutment 15° TLA-15-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.5, 2.5], "angulations_deg": [15],
     "torque_ncm": 30, "catalog_code": "3511",
     "indication": "Anterior axis correction"},
    {"type": "final_abutment", "subtype": "Angled Abutment 25° TLA-25-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.5, 2.5], "angulations_deg": [25],
     "torque_ncm": 30, "catalog_code": "3514",
     "indication": "Steep axis correction"},

    # Multi-unit abutments — straight + 17° + 30°
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Straight Abutment TCT-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.5, 1.5, 2.5], "torque_ncm": 30,
     "catalog_code": "3870",
     "indication": "Up to 30° divergence between teeth — full-arch screw-retained"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Straight HBC-H0.75-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 1.5, 2.5], "torque_ncm": 30,
     "catalog_code": "3876", "indication": "Single-implant screw-retained"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 17° AU 17-CS",
     "platform": "CS", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [17],
     "torque_ncm": 30, "catalog_code": "3862",
     "indication": "All-on-X tilted posterior implants"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 30° AU 30-CS",
     "platform": "CS", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [30],
     "torque_ncm": 30, "catalog_code": "3867",
     "indication": "Distal-tilted All-on-4/6 implants"},

    # Ti-base (engaged + non-engaged + Sirona)
    {"type": "ti_base", "subtype": "Straight Ti-Base (Engaged) TB-AR-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 1.5, 2.5], "diameter_mm": 4.87,
     "torque_ncm": 30, "catalog_code": "3832", "cad_cam": True,
     "indication": "Single-tooth CAD/CAM crown"},
    {"type": "ti_base", "subtype": "Straight Ti-Base (Non-Engaged) TB-R-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 1.5, 2.5], "diameter_mm": 4.87,
     "torque_ncm": 30, "catalog_code": "3833", "cad_cam": True,
     "indication": "Splinted bridge / bar"},
    {"type": "ti_base", "subtype": "Sirona-Compatible Ti-Base CSTB-CS-SI",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm": 30, "catalog_code": "3856", "cad_cam": True,
     "indication": "Cerec / inLab digital workflow"},

    # Scan bodies
    {"type": "scanbody", "subtype": "Dual-Use Scan Body IOSB-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "3837",
     "indication": "Lab + intra-oral digital impression"},
    {"type": "scanbody", "subtype": "Sirona Scan Post CS-CS-SI",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "3857",
     "indication": "Cerec / inLab scanning"},

    # Impression copings
    {"type": "impression_coping",
     "subtype": "Open Tray Coping Short CTT-CS",
     "platform": "CS", "material": ["plastic"], "retention": ["screw"],
     "diameter_mm": 4.7, "length_mm": 15, "torque_ncm_max": 10,
     "catalog_code": "3455", "indication": "Pickup impression — short body"},
    {"type": "impression_coping",
     "subtype": "Open Tray Coping Long CTTS-CS",
     "platform": "CS", "material": ["plastic"], "retention": ["screw"],
     "diameter_mm": 4.7, "length_mm": 19, "torque_ncm_max": 10,
     "catalog_code": "3456", "indication": "Pickup impression — long body"},
    {"type": "impression_coping",
     "subtype": "Closed Tray Coping Short SCTT-CS",
     "platform": "CS", "material": ["plastic"], "retention": ["friction"],
     "diameter_mm": 3.2, "length_mm": 12, "catalog_code": "3450",
     "indication": "Indirect transfer — short"},
    {"type": "impression_coping",
     "subtype": "Closed Tray Coping Long LCTT-CS",
     "platform": "CS", "material": ["plastic"], "retention": ["friction"],
     "diameter_mm": 3.2, "length_mm": 15, "catalog_code": "3451",
     "indication": "Indirect transfer — long"},

    # Analog
    {"type": "analog", "subtype": "Implant Analog IA-CS",
     "platform": "CS", "material": ["titanium"], "diameter_mm": 3.75,
     "catalog_code": "3459", "indication": "Stone / 3D-printed lab models"},

    # Prosthetic screws
    {"type": "prosthetic_screw",
     "subtype": "Abutment Screw STLA-CS (Clinic)",
     "platform": "CS", "material": ["titanium"], "torque_ncm": 30,
     "catalog_code": "3510", "indication": "Definitive abutment fixation"},
    {"type": "prosthetic_screw", "subtype": "Retrieval Screw RS",
     "platform": "CS", "material": ["titanium"],
     "catalog_code": "5110", "indication": "Stripped-screw retrieval"},

    # Temporary / casting
    {"type": "temporary_abutment",
     "subtype": "Temporary Engaged Ti TA-AR-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm": 25, "catalog_code": "3532",
     "indication": "Engaged provisional — single tooth (≤180 days)"},
    {"type": "temporary_abutment",
     "subtype": "Temporary Non-Engaged Ti TA-R-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm": 25, "catalog_code": "3533",
     "indication": "Non-engaged provisional — splinted (≤180 days)"},
    {"type": "temporary_abutment", "subtype": "PEEK Temporary TTA-N",
     "platform": "CS", "material": ["PEEK"], "retention": ["screw"],
     "torque_ncm": 15, "catalog_code": "5216",
     "indication": "Cement / screw-retained provisional (≤180 days)"},
    {"type": "casting_abutment",
     "subtype": "Co-Cr Casting Abutment CoCr-AR-CHCS",
     "platform": "CS", "material": ["cobalt_chrome"], "retention": ["screw"],
     "torque_ncm": 30, "catalog_code": "CoCr-AR-CHCS",
     "indication": "Engaged casting — burn out titanium base before casting"},

    # Pre-milled blanks
    {"type": "pre_milled_blank",
     "subtype": "Pre-milled Blank Standard BA-PF-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 11.5, "torque_ncm": 30, "catalog_code": "3854",
     "cad_cam": True, "indication": "PreFace® holder — single tooth"},
    {"type": "pre_milled_blank",
     "subtype": "Pre-milled Blank Wide WBA-PF-CS",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 15.8, "torque_ncm": 30, "catalog_code": "3855",
     "cad_cam": True, "indication": "PreFace® holder — molars / wide emergence"},

    # Overdenture attachments
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Straight Abutment",
     "platform": "CS", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 2, 3, 4], "torque_ncm": 30,
     "catalog_code": "3710",
     "indication": "Removable overdenture — Locator-style attachment"},
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Retentive Caps (Violet/Clear/Pink/Yellow)",
     "platform": "CS", "material": ["nylon"], "retention": ["friction"],
     "indication": "Strong / standard / soft / extra-soft retention"},
    {"type": "overdenture_attachment",
     "subtype": "Straight Ball Attachment TB",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3, 4, 5, 6], "torque_ncm": 30,
     "catalog_code": "6260", "indication": "Ball-and-socket overdenture"},
    {"type": "overdenture_attachment",
     "subtype": "Angled Ball Attachment TBAA2",
     "platform": "CS", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [3, 4], "torque_ncm": 30,
     "catalog_code": "6304",
     "indication": "Ball oriented to flat hex face — divergent ridges"},

    # Burnout sleeves
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Engaged PST-N-AR",
     "platform": "CS", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5217", "indication": "Engaged casting sleeve"},
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Non-Engaged PST-N",
     "platform": "CS", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5218", "indication": "Non-engaged casting sleeve"},
]

_CHC_COMPONENTS: List[Dict] = [
    {"type": "cover_screw", "subtype": "Cover Screw SF-N",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SF-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing"},
    {"type": "cover_screw", "subtype": "Cover Screw (Black-Coated) SFT-N",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SFT-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing — colour-coded"},

    # Healing abutments — Ø 3.4 / 3.8 / 4.2
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø3.4 mm",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 3.4, "gingival_heights_mm": [2, 3, 5],
     "torque_ncm": 10, "catalog_code": "HA-D3.4-*-CHC",
     "indication": "Narrow emergence (NICE / NeO CHC narrow ridge)"},
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø3.8 mm",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [2, 3, 5],
     "torque_ncm": 10, "catalog_code": "HA-D3.8-*-CHC",
     "indication": "Standard emergence"},
    {"type": "healing_abutment", "subtype": "Healing Abutment Ø4.2 mm",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.2, "gingival_heights_mm": [2, 3, 5],
     "torque_ncm": 10, "catalog_code": "HA-D4.2-*-CHC",
     "indication": "Wide emergence"},

    # Straight + Anatomic + Angled
    {"type": "final_abutment",
     "subtype": "Esthetic Simply Straight Abutment H1.0",
     "platform": "CHC", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1], "torque_ncm": 30,
     "catalog_code": "7350",
     "indication": "Anterior cement-retained — minimal cuff"},
    {"type": "final_abutment",
     "subtype": "Esthetic Standard Abutment Ø3.2",
     "platform": "CHC", "material": ["titanium"], "retention": ["cement"],
     "diameter_mm": 3.2, "torque_ncm": 30,
     "catalog_code": "7356",
     "indication": "Esthetic zone — standard emergence"},
    {"type": "final_abutment", "subtype": "Anatomic Angled 15° CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.1], "angulations_deg": [15], "torque_ncm": 30,
     "catalog_code": "7360", "indication": "Anterior axis correction"},
    {"type": "final_abutment", "subtype": "Anatomic Angled 25° CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.1], "angulations_deg": [25], "torque_ncm": 30,
     "catalog_code": "7362", "indication": "Steep axis correction"},

    # MUA — straight + 17° + 30°
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Straight TCT-N CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 1.5, 2.5, 3.5, 4.5, 5.5],
     "torque_ncm": 30, "catalog_code": "5242",
     "indication": "Full-arch screw-retained — up to 30° divergence"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 17° AU 17 CHC",
     "platform": "CHC", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [17],
     "torque_ncm": 30, "catalog_code": "7482",
     "indication": "All-on-X tilted posterior"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 30° AU 30 CHC",
     "platform": "CHC", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [30],
     "torque_ncm": 30, "catalog_code": "7487",
     "indication": "Distal-tilted All-on-4/6"},

    # Ti-base — straight engaged / non-engaged / angled / Sirona
    {"type": "ti_base", "subtype": "Straight Ti-Base (Engaged) CCTB-CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.7, 2.5], "diameter_mm": 5,
     "torque_ncm": 30, "catalog_code": "5026", "cad_cam": True,
     "indication": "Single-tooth CAD/CAM"},
    {"type": "ti_base", "subtype": "Straight Ti-Base (Non-Engaged) CCTB-CHC-R",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.7, 2.5], "diameter_mm": 5,
     "torque_ncm": 30, "catalog_code": "5027", "cad_cam": True,
     "indication": "Splinted bridge / bar"},
    {"type": "ti_base", "subtype": "Angled Ti-Base ACCTB-CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [5], "length_mm": 5.5,
     "torque_ncm": 30, "catalog_code": "5006", "cad_cam": True,
     "indication": "Single tooth on an angle"},
    {"type": "ti_base", "subtype": "Sirona Ti-Base CCTB-CHC-SI",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm": 30, "catalog_code": "4982", "cad_cam": True,
     "indication": "Cerec / inLab"},

    # Scan body (dual + Sirona)
    {"type": "scanbody", "subtype": "Dual-Use Scan Body SB-CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "5021",
     "indication": "Lab + intra-oral digital impression"},
    {"type": "scanbody", "subtype": "Sirona Scan Post CCSP-CHC-SI",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "4985",
     "indication": "Cerec / inLab"},

    # Impression copings
    {"type": "impression_coping",
     "subtype": "Open Tray Transfer HLTO-CHC",
     "platform": "CHC", "material": ["plastic"], "retention": ["screw"],
     "diameter_mm": 5, "length_mm": 12, "torque_ncm_max": 10,
     "catalog_code": "7335", "indication": "Pickup impression"},
    {"type": "impression_coping",
     "subtype": "Closed Tray Transfer HLTS-CHC",
     "platform": "CHC", "material": ["plastic"], "retention": ["friction"],
     "length_mm": 10.5, "catalog_code": "7333",
     "indication": "Indirect transfer"},

    # Analog
    {"type": "analog", "subtype": "Implant Analog IA-CHC",
     "platform": "CHC", "material": ["titanium"],
     "catalog_code": "7338", "indication": "Stone / printed lab models"},

    # Prosthetic screws
    {"type": "prosthetic_screw",
     "subtype": "Abutment Screw STLA-CHC", "platform": "CHC",
     "material": ["titanium"], "torque_ncm": 30, "catalog_code": "7345",
     "indication": "Definitive fixation"},
    {"type": "prosthetic_screw", "subtype": "Retrieval Screw RS-CHC",
     "platform": "CHC", "material": ["titanium"], "catalog_code": "7400",
     "indication": "Stripped-screw retrieval"},

    # Temporary
    {"type": "temporary_abutment", "subtype": "PEEK Temporary TTA-N",
     "platform": "CHC", "material": ["PEEK"], "retention": ["screw"],
     "torque_ncm": 15, "catalog_code": "5216",
     "indication": "Provisional restoration (≤180 days)"},

    # Pre-milled
    {"type": "pre_milled_blank", "subtype": "Pre-milled Blank BA-PF-CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 11.5, "torque_ncm": 30, "catalog_code": "4990",
     "cad_cam": True, "indication": "PreFace® holder"},

    # Overdenture
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Straight Abutment CHC",
     "platform": "CHC", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [0.5, 1, 2, 3, 4, 5], "torque_ncm": 20,
     "catalog_code": "7470",
     "indication": "Removable overdenture (max 20 Ncm on CHC)"},
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Retentive Caps (Violet/Clear/Pink/Yellow)",
     "platform": "CHC", "material": ["nylon"], "retention": ["friction"],
     "indication": "Strong / standard / soft / extra-soft retention"},
    {"type": "overdenture_attachment",
     "subtype": "Straight Ball Attachment TB1-CHC",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3, 4, 5, 6], "torque_ncm": 20,
     "catalog_code": "7403", "indication": "Ball-and-socket overdenture"},
    {"type": "overdenture_attachment",
     "subtype": "Angled Ball Attachment TBAA2",
     "platform": "CHC", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [3, 4], "torque_ncm": 20,
     "catalog_code": "6304",
     "indication": "Divergent ridge — ball oriented to flat hex face"},

    # Burnout
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Engaged PST-N-AR",
     "platform": "CHC", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5217", "indication": "Engaged casting sleeve"},
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Non-Engaged PST-N",
     "platform": "CHC", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5218", "indication": "Non-engaged casting sleeve"},
]

_IH_COMPONENTS: List[Dict] = [
    {"type": "cover_screw", "subtype": "Cover Screw SF-N",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SF-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing"},
    {"type": "cover_screw", "subtype": "Cover Screw (Black-Coated) SFT-N",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "catalog_code": "SFT-N", "torque_ncm": 10,
     "indication": "Two-stage submerged healing — colour-coded"},

    # Healing abutments — diameters 3.85 / 4.6 / 5.0 / 5.5 / 6.0 / 7.0 mm × cuff 2-7
    {"type": "healing_abutment", "subtype": "Slim Healing Abutment HSS",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 3.85, "gingival_heights_mm": [3, 4, 5],
     "torque_ncm": 10, "catalog_code": "HSS3 / HSS4 / HSS5",
     "indication": "Narrow ridge / esthetic-zone slim emergence"},
    {"type": "healing_abutment", "subtype": "Standard Healing Abutment HS Ø4.6",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [2, 3, 4, 5, 6, 7],
     "torque_ncm": 10, "catalog_code": "HS2 / HS3 / HS4 / HS5 / HS6 / HS7",
     "indication": "Standard emergence — most cases"},
    {"type": "healing_abutment", "subtype": "Wide Healing Abutment HS Ø5.0",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [3, 5],
     "torque_ncm": 10, "catalog_code": "HS5-3 / HS5-5",
     "indication": "Wide emergence — premolars / molars"},
    {"type": "healing_abutment", "subtype": "Wide Healing Abutment HS Ø5.5",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [3, 5],
     "torque_ncm": 10, "catalog_code": "HS5.5-3 / HS5.5-5",
     "indication": "Wide emergence — large molars"},
    {"type": "healing_abutment", "subtype": "Wide Healing Abutment HS Ø6.0",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [3, 5],
     "torque_ncm": 10, "catalog_code": "HS6-3 / HS6-5",
     "indication": "Extra-wide emergence"},
    {"type": "healing_abutment", "subtype": "Wide Healing Abutment HS Ø7.0",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 7.0, "gingival_heights_mm": [3],
     "torque_ncm": 10, "catalog_code": "HS7-3",
     "indication": "Extra-wide emergence — molars"},

    # Straight final abutments
    {"type": "final_abutment", "subtype": "Straight Ti Abutment TLA",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.7], "diameter_mm": 4.5, "length_mm": 8.5,
     "torque_ncm": 30, "catalog_code": "5030",
     "indication": "Standard cement-retained crown"},
    {"type": "final_abutment", "subtype": "Long Straight Ti Abutment TLAL",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.7], "diameter_mm": 4.5, "length_mm": 12.5,
     "torque_ncm": 30, "catalog_code": "5140",
     "indication": "Long-span / deep margin cement crown"},
    {"type": "final_abutment", "subtype": "Esthetic Step Straight TLASP",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1, 2, 3, 4], "diameter_mm": 4.8,
     "torque_ncm": 30, "catalog_code": "5366",
     "indication": "Stepped emergence — esthetic zone"},
    {"type": "final_abutment", "subtype": "Slim Straight TLAS",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [0.8], "diameter_mm": 3.85, "length_mm": 8.5,
     "torque_ncm": 30, "catalog_code": "5150",
     "indication": "Narrow-ridge cement crown"},

    # Angled final abutments — 15° / 25° / 35°
    {"type": "final_abutment", "subtype": "Angled Ti Abutment 15° TLA-15",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.7], "angulations_deg": [15], "length_mm": 8.5,
     "torque_ncm": 30, "catalog_code": "5090",
     "indication": "Anterior axis correction"},
    {"type": "final_abutment", "subtype": "Angled Ti Abutment 25° TLA-25",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.8], "angulations_deg": [25], "length_mm": 8.5,
     "torque_ncm": 30, "catalog_code": "5130",
     "indication": "Mid-range axis correction"},
    {"type": "final_abutment", "subtype": "Angled Ti Abutment 35° TLA-35",
     "platform": "IH", "material": ["titanium"], "retention": ["cement"],
     "gingival_heights_mm": [1.45], "angulations_deg": [35], "length_mm": 10,
     "torque_ncm": 30, "catalog_code": "5136",
     "indication": "Maximum axis correction — paired with STLASH screw"},

    # Multi-unit abutments — straight + 17° + 30°
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Straight TCT-N",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.75, 1.6, 2.6, 3.6, 4.6, 5.6],
     "torque_ncm": 30, "catalog_code": "5221",
     "indication": "Full-arch / bar — up to 30° divergence"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 17° AU 17-IH",
     "platform": "IH", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [17],
     "torque_ncm": 30, "catalog_code": "5432",
     "indication": "All-on-X tilted posterior implant"},
    {"type": "multi_unit_abutment",
     "subtype": "Multi-Unit Angled 30° AU 30-IH",
     "platform": "IH", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1.5, 2.5, 3.5], "angulations_deg": [30],
     "torque_ncm": 30, "catalog_code": "5437",
     "indication": "Distal-tilted All-on-4/6"},

    # Ti-base — straight engaged / non-engaged / wide / wide non-engaged / angled / Sirona
    {"type": "ti_base", "subtype": "Straight Ti-Base CCTB",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.7], "diameter_mm": 5.7,
     "torque_ncm": 30, "catalog_code": "5024", "cad_cam": True,
     "indication": "Single-tooth CAD/CAM"},
    {"type": "ti_base", "subtype": "Straight Ti-Base CCTB-2.5",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [2.5], "diameter_mm": 6.5,
     "torque_ncm": 30, "catalog_code": "4951", "cad_cam": True,
     "indication": "Tall-cuff single tooth"},
    {"type": "ti_base", "subtype": "Wide Ti-Base WCCTB",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.7], "diameter_mm": 4.2,
     "torque_ncm": 30, "catalog_code": "5007", "cad_cam": True,
     "indication": "Wide single tooth"},
    {"type": "ti_base", "subtype": "Wide Ti-Base Non-Engaged WCCTB-R",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [0.7], "diameter_mm": 4.2,
     "torque_ncm": 30, "catalog_code": "5008", "cad_cam": True,
     "indication": "Splinted bridge / bar"},
    {"type": "ti_base", "subtype": "Angled Ti-Base ACCTB",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [5], "length_mm": 5.5,
     "torque_ncm": 30, "catalog_code": "5005", "cad_cam": True,
     "indication": "Single tooth on an angle"},
    {"type": "ti_base", "subtype": "Sirona Ti-Base CCTB-IH-SI",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm": 30, "catalog_code": "4980", "cad_cam": True,
     "indication": "Cerec / inLab"},

    # Scan bodies
    {"type": "scanbody", "subtype": "Dual-Use Scan Body SB-IH",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "5019",
     "indication": "Lab + intra-oral digital impression"},
    {"type": "scanbody", "subtype": "Sirona Scan Post CCSP-IH-SI",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "4984",
     "indication": "Cerec / inLab"},

    # Impression copings
    {"type": "impression_coping", "subtype": "Open Tray HLTO",
     "platform": "IH", "material": ["plastic"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "5061",
     "indication": "Pickup impression — short"},
    {"type": "impression_coping", "subtype": "Open Tray Long HLTOS",
     "platform": "IH", "material": ["plastic"], "retention": ["screw"],
     "torque_ncm_max": 10, "catalog_code": "5171",
     "indication": "Pickup impression — long"},
    {"type": "impression_coping", "subtype": "Closed Tray HLT",
     "platform": "IH", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5170", "indication": "Indirect transfer — short"},
    {"type": "impression_coping", "subtype": "Closed Tray Long HLTLS",
     "platform": "IH", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5062", "indication": "Indirect transfer — long"},

    # Analog
    {"type": "analog", "subtype": "Implant Analog IA",
     "platform": "IH", "material": ["titanium"], "diameter_mm": 4.2,
     "catalog_code": "5080",
     "indication": "Compatible with all IH diameters"},
    {"type": "analog", "subtype": "Wide Implant Analog IA5",
     "platform": "IH", "material": ["titanium"], "diameter_mm": 5.0,
     "catalog_code": "5280", "indication": "For Ø5.0 Wide Platform"},

    # Prosthetic screws
    {"type": "prosthetic_screw",
     "subtype": "Abutment Screw STLAS (Clinic)",
     "platform": "IH", "material": ["titanium"], "torque_ncm": 30,
     "catalog_code": "STLAS", "indication": "Definitive abutment fixation"},
    {"type": "prosthetic_screw",
     "subtype": "Lab Screw STLAT (Lab-only, coated)",
     "platform": "IH", "material": ["titanium"], "torque_ncm": 30,
     "catalog_code": "STLAT", "indication": "Specially coated — lab use only"},
    {"type": "prosthetic_screw",
     "subtype": "Long Screw STLASH (TLA-35 only)",
     "platform": "IH", "material": ["titanium"], "torque_ncm": 30,
     "catalog_code": "STLASH",
     "indication": "Use exclusively with TLA-35 angled abutment"},
    {"type": "prosthetic_screw", "subtype": "Retrieval Screw RS",
     "platform": "IH", "material": ["titanium"], "catalog_code": "RS",
     "indication": "Stripped-screw retrieval"},

    # Temporary
    {"type": "temporary_abutment", "subtype": "PEEK Temporary TTA-N",
     "platform": "IH", "material": ["PEEK"], "retention": ["screw"],
     "torque_ncm": 15, "catalog_code": "5216",
     "indication": "Cement / screw-retained provisional (≤180 days)"},
    {"type": "temporary_abutment",
     "subtype": "PEEK Temporary Straight TPA1/TPA2/TPA3",
     "platform": "IH", "material": ["PEEK"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3], "torque_ncm": 15,
     "catalog_code": "TPA1/TPA2/TPA3",
     "indication": "Cuff-height-specific provisional"},
    {"type": "temporary_abutment",
     "subtype": "PEEK Temporary Angled 15° TPA15",
     "platform": "IH", "material": ["PEEK"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3], "angulations_deg": [15],
     "torque_ncm": 15, "catalog_code": "TPA15-1/-2/-3",
     "indication": "Angled provisional — anterior cases"},
    {"type": "temporary_abutment",
     "subtype": "PEEK Temporary Angled 25° TPA25",
     "platform": "IH", "material": ["PEEK"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2], "angulations_deg": [25],
     "torque_ncm": 15, "catalog_code": "TPA25-1/-2",
     "indication": "Angled provisional — steep axis"},

    # Casting
    {"type": "casting_abutment",
     "subtype": "Co-Cr Casting Engaged TLABCC",
     "platform": "IH", "material": ["cobalt_chrome"], "retention": ["screw"],
     "torque_ncm": 20, "catalog_code": "TLABCC",
     "indication": "Engaged casting — single tooth"},
    {"type": "casting_abutment",
     "subtype": "Co-Cr Casting Non-Engaged TLABCC-R",
     "platform": "IH", "material": ["cobalt_chrome"], "retention": ["screw"],
     "torque_ncm": 20, "catalog_code": "TLABCC-R",
     "indication": "Non-engaged casting — bridge"},

    # Pre-milled
    {"type": "pre_milled_blank", "subtype": "Pre-milled Blank BA-PF-IH",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 11.5, "torque_ncm": 30, "catalog_code": "4988",
     "cad_cam": True, "indication": "PreFace® holder — single tooth"},
    {"type": "pre_milled_blank", "subtype": "Pre-milled Blank Wide WBA-PF-IH",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 15.8, "torque_ncm": 30, "catalog_code": "4989",
     "cad_cam": True, "indication": "PreFace® holder — wide emergence"},

    # Overdenture
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Straight Abutment IH",
     "platform": "IH", "material": ["titanium_alloy"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3, 4, 5], "torque_ncm": 30,
     "catalog_code": "4867",
     "indication": "Removable overdenture — Locator-style"},
    {"type": "overdenture_attachment",
     "subtype": "ALPHALOC Retentive Caps (Violet/Clear/Pink/Yellow)",
     "platform": "IH", "material": ["nylon"], "retention": ["friction"],
     "indication": "Strong / standard / soft / extra-soft retention"},
    {"type": "overdenture_attachment",
     "subtype": "Straight Ball Attachment TB",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [1, 2, 3, 4, 5, 6], "torque_ncm": 30,
     "catalog_code": "6260", "indication": "Ball-and-socket overdenture"},
    {"type": "overdenture_attachment",
     "subtype": "Angled Ball Attachment TBAA2",
     "platform": "IH", "material": ["titanium"], "retention": ["screw"],
     "gingival_heights_mm": [3, 4], "torque_ncm": 30,
     "catalog_code": "6304",
     "indication": "Divergent ridge — ball oriented to flat hex face"},

    # Burnout
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Engaged PST-N-AR",
     "platform": "IH", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5217", "indication": "Engaged casting sleeve"},
    {"type": "burnout_sleeve",
     "subtype": "Burnout Sleeve Non-Engaged PST-N",
     "platform": "IH", "material": ["plastic"], "retention": ["friction"],
     "catalog_code": "5218", "indication": "Non-engaged casting sleeve"},
]


COMPONENTS_BY_PLATFORM: Dict[str, List[Dict]] = {
    "CS": _CS_COMPONENTS,
    "CHC": _CHC_COMPONENTS,
    "IH": _IH_COMPONENTS,
}


# Map each AlphaBio system to its prosthetic platform.
SYSTEM_PLATFORM: Dict[str, str] = {
    "SPI": "IH",
    "NeO Conical Standard Connection": "CS",
    "NeO Conical Hex Connection": "CHC",
    "NeO Internal Hex Connection": "IH",
    "ICE": "IH",
    "ATID": "IH",
    "DFI": "IH",
    "NICE": "CHC",
}


def expanded_components_for(system_name: str) -> List[Dict]:
    """Return a fresh deep-copyable component list for an Alpha-Bio system."""
    import copy
    platform = SYSTEM_PLATFORM.get(system_name)
    if platform is None:
        return []
    return copy.deepcopy(COMPONENTS_BY_PLATFORM[platform])
