"""iter-162 — rich prosthetic catalog data for Cowellmedi (INNO line + Mini Plus),
MIS LANCE+, and the Osstem internal-hex / internal-octa shared suites.

This module is **data-only** — no DB writes. It exposes:
  • Component arrays (COWELL_COMPONENTS, OSSTEM_INTERNAL_HEX_COMPONENTS, etc.)
  • Pre-built curated records for new Cowell keys (Submerged / Submerged Narrow /
    Mini Plus) that are not yet present in the base seed.
  • Apply-overrides helper used by `implant_catalog_seed.py` to ensure the
    startup seeder does not regress these rich definitions back to stubs.

Run `_seed_iter162.py` (or just restart the backend) to push this data into
MongoDB. Admin manual edits remain protected — the startup seeder only
overwrites docs whose `updated_by` is empty/"seed".
"""
from typing import Any, Dict, List

# ───────────── Cowellmedi shared INNO prosthetic suite ─────────────
COWELL_COMPONENTS: List[Dict[str, Any]] = [
    {"type": "cover_screw", "subtype": "Cover Screw", "gingival_heights_mm": [1.7, 2.7, 3.7],
     "material": ["titanium_alloy"], "torque_ncm": [5, 10], "retention": ["screw"],
     "indication": "Seals conical interface during submerged healing."},
    {"type": "healing_abutment", "subtype": "Healing Abutment",
     "gingival_heights_mm": [0.5, 1, 2, 3, 4, 5, 7], "material": ["titanium_alloy"],
     "torque_ncm": [5, 10], "retention": ["screw"]},
    {"type": "healing_abutment", "subtype": "Volume-up Healing Abutment",
     "gingival_heights_mm": [7.9], "material": ["titanium_alloy"], "torque_ncm": [25, 35]},
    {"type": "temporary_cylinder", "subtype": "Temporary Abutment",
     "gingival_heights_mm": [10], "material": ["titanium_alloy"], "torque_ncm": [20],
     "retention": ["screw"]},
    {"type": "temporary_cylinder", "subtype": "Easy Temporary Abutment",
     "gingival_heights_mm": [10], "material": ["titanium_alloy"], "torque_ncm": [20]},
    {"type": "final_abutment", "subtype": "Cemented Abutment",
     "gingival_heights_mm": [4, 5.5, 7], "material": ["titanium_alloy"], "torque_ncm": [30],
     "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "Angulated Abutment",
     "gingival_heights_mm": [8], "angulation_deg": [15, 25],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["screw"]},
    {"type": "final_abutment", "subtype": "Beauty-up Abutment",
     "gingival_heights_mm": [5], "angulation_deg": [15, 25],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["screw"]},
    {"type": "final_abutment", "subtype": "Milling Abutment",
     "gingival_heights_mm": [7], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True, "retention": ["screw"]},
    {"type": "final_abutment", "subtype": "Meta G UCLA Abutment",
     "gingival_heights_mm": [12], "material": ["CCM_alloy"], "torque_ncm": [30],
     "retention": ["screw"], "indication": "Castable cobalt-chromium UCLA."},
    {"type": "final_abutment", "subtype": "Plastic UCLA Abutment",
     "gingival_heights_mm": [14], "material": ["PMMA"], "torque_ncm": [30],
     "retention": ["screw"]},
    {"type": "multi_unit_abutment", "subtype": "Multi S Abutment (Straight)",
     "gingival_heights_mm": [3, 4, 5], "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "Multi A Abutment (Angled)",
     "gingival_heights_mm": [3, 4, 5], "angulation_deg": [15, 30],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "ti_base", "subtype": "Hybrid Ti-Base S (3.75 mm)",
     "gingival_heights_mm": [3.75], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True, "retention": ["screw"]},
    {"type": "ti_base", "subtype": "Hybrid Ti-Base L (5.5 mm)",
     "gingival_heights_mm": [5.5], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True, "retention": ["screw"]},
    {"type": "ti_base", "subtype": "Hybrid Ti-Block (mill blank)",
     "gingival_heights_mm": [10, 12, 14], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True},
    {"type": "ti_base", "subtype": "Lock Hybrid Ti-Base",
     "gingival_heights_mm": [8.5], "material": ["titanium_alloy"], "torque_ncm": [15, 20],
     "cad_cam": True, "retention": ["locking_mechanism"]},
    {"type": "ti_base", "subtype": "Multi Hybrid Ti-Base",
     "gingival_heights_mm": [0.5, 1.5], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True},
    {"type": "scanbody", "subtype": "Scanbody",
     "gingival_heights_mm": [8], "material": ["titanium_alloy"], "torque_ncm": [15, 20]},
    {"type": "scanbody", "subtype": "Multi Scanbody",
     "gingival_heights_mm": [8], "material": ["titanium_alloy"]},
    {"type": "scanbody", "subtype": "Lock Scanbody",
     "gingival_heights_mm": [8], "material": ["titanium_alloy"], "torque_ncm": [15, 20]},
    {"type": "impression_coping", "subtype": "Pick-up Impression Coping (Open Tray)",
     "gingival_heights_mm": [9, 11], "material": ["titanium_alloy"]},
    {"type": "impression_coping", "subtype": "Transfer Post (Closed Tray)",
     "gingival_heights_mm": [11, 15], "material": ["titanium_alloy"]},
    {"type": "analog", "subtype": "Lab Analog",
     "gingival_heights_mm": [4, 5.5, 7], "material": ["titanium_alloy"]},
    {"type": "analog", "subtype": "Digital Analog (3D-print compatible)",
     "gingival_heights_mm": [3.9], "material": ["titanium_alloy"]},
    {"type": "analog", "subtype": "Replica",
     "gingival_heights_mm": [12], "material": ["titanium_alloy"]},
    {"type": "prosthetic_screw", "subtype": "Prosthetic Screw",
     "gingival_heights_mm": [2.15, 2.45], "material": ["titanium_alloy"]},
    {"type": "overdenture_attachment", "subtype": "Lock Abutment (Locator-style)",
     "gingival_heights_mm": [0.5, 1, 2, 3, 4], "material": ["titanium_alloy"],
     "retention": ["locking_mechanism"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Abutment",
     "gingival_heights_mm": [4], "material": ["titanium_alloy"], "torque_ncm": [30],
     "retention": ["o_ring"]},
    {"type": "overdenture_attachment", "subtype": "Sonator S Abutment (Straight)",
     "gingival_heights_mm": [1.5, 2, 3, 4, 5, 6], "material": ["titanium_alloy"],
     "torque_ncm": [30], "retention": ["variable_retention_male"]},
    {"type": "overdenture_attachment", "subtype": "Sonator A Abutment (Angled 15°)",
     "gingival_heights_mm": [1.5, 3.0], "angulation_deg": [15],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["variable_retention_male"]},
]

COWELL_FEATURES: List[str] = [
    "Sandblasted, Large-grit, Acid-etched and Super-Hydrophilised (SLA-SH®) surface",
    "Nano/CaP soaking technology",
    "Macro-pore + micro-pore mimicking etched enamel rod",
    "Even distribution of roughness; no surface destruction up to 120 N.cm torque",
    "Internal hex (Taper 11° / Hex 2.5) connection",
]

# Cowell new systems not present in base seed. Each will be built into a curated
# record by `_build_cowell_record()` below.
_COWELL_SYSTEMS: List[Dict[str, Any]] = [
    {
        "key": "Cowell Medi|INNO Submerged",
        "name": "INNO Submerged (SLA-SH®)",
        "diameters": [3.5, 4.0, 4.5, 5.0, 6.0],
        "lengths": [7, 8, 10, 12, 14, 16, 18],
        "notes": "Internal hex (Taper 11° / Hex 2.5) interchangeable with hexagonal morse-tapered fixtures. No-Mount and Pre-Mount options available.",
    },
    {
        "key": "Cowell Medi|INNO Submerged Narrow",
        "name": "INNO Submerged Narrow (SLA-SH®)",
        "diameters": [3.1, 3.3],
        "lengths": [8, 10, 12, 14],
        "notes": "Narrow internal hex (Taper 11° / Hex 2.1). Hexagon size differs from standard INNO Submerged.",
    },
    {
        "key": "Cowell Medi|Mini Plus",
        "name": "Mini Plus 1-Piece (SLA-SH®)",
        "diameters": [2.0, 2.5, 3.0, 4.0],
        "lengths": [10, 12, 14],
        "notes": "1-piece mini implant for narrow mandibular anterior spaces and edentulous arches. Top Anti-Rotation Square + cutting grooves at 5 mm and 7 mm for height alteration.",
        "components_override": [
            {"type": "overdenture_attachment", "subtype": "1P Ball Abutment (integral)",
             "gingival_heights_mm": [4.2], "material": ["titanium_alloy"],
             "torque_ncm": [30], "retention": ["o_ring"]},
            {"type": "overdenture_attachment", "subtype": "Ball Outer Cap"},
            {"type": "overdenture_attachment", "subtype": "Ball Inner Cap (variable retention)"},
            {"type": "temporary_cylinder", "subtype": "Protection Cap",
             "gingival_heights_mm": [7, 9, 11], "material": ["titanium_alloy"]},
            {"type": "impression_coping", "subtype": "Impression Coping",
             "material": ["titanium_alloy"]},
            {"type": "analog", "subtype": "Lab Analog", "material": ["titanium_alloy"]},
        ],
    },
]


def _build_cowell_record(s: Dict[str, Any]) -> Dict[str, Any]:
    name = s["name"]
    conn_type = "internal_hex" if ("Submerged" in name or "External" in name or "Mini" in name) else "internal_octa"
    return {
        "key": s["key"],
        "brand": "Cowell Medi",
        "name": name,
        "connection": {"type": conn_type, "subtype": "morse_taper"},
        "platform_switching": True,
        "features": list(COWELL_FEATURES),
        "implant": {
            "diameters_mm": s["diameters"], "lengths_mm": s["lengths"],
            "bone_types": ["all"], "healing_modes": ["submerged", "non_submerged"],
        },
        "components": s.get("components_override", COWELL_COMPONENTS),
        "compatibility_notes": s["notes"],
    }


COWELL_NEW_RECORDS: List[Dict[str, Any]] = [_build_cowell_record(s) for s in _COWELL_SYSTEMS]


# ───────────── Osstem shared internal-hex prosthetic suite ─────────────
OSSTEM_INTERNAL_HEX_COMPONENTS: List[Dict[str, Any]] = [
    {"type": "cover_screw", "subtype": "Cover Screw — Mini/Regular/Wide",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"],
     "torque_ncm": [10], "retention": ["screw"]},
    {"type": "healing_abutment", "subtype": "Healing Abutment (Mini)",
     "platforms_mm": [3.5], "gingival_heights_mm": [3, 4, 5, 6, 7],
     "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "healing_abutment", "subtype": "Healing Abutment (Regular)",
     "platforms_mm": [4.5], "gingival_heights_mm": [3, 4, 5, 6, 7, 8],
     "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "healing_abutment", "subtype": "Healing Abutment (Wide)",
     "platforms_mm": [5.5], "gingival_heights_mm": [3, 4, 5, 6, 7, 8],
     "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "temporary_cylinder", "subtype": "Transfer Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "temporary_cylinder", "subtype": "FreeForm ST Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "torque_ncm": [30],
     "indication": "Customizable temporary abutment for chairside provisional crowns."},
    {"type": "final_abutment", "subtype": "GoldCast Abutment (UCLA — castable)",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["gold_alloy"], "torque_ncm": [30],
     "retention": ["castable"]},
    {"type": "final_abutment", "subtype": "NP-Cast Abutment (non-precious castable)",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["base_metal_alloy"], "torque_ncm": [30],
     "retention": ["castable"]},
    {"type": "final_abutment", "subtype": "Link Abutment for Lab",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True},
    {"type": "final_abutment", "subtype": "Link Abutment for Cerec",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "torque_ncm": [30],
     "cad_cam": True},
    {"type": "final_abutment", "subtype": "ZioCera Abutment (zirconia)",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["zirconia"], "torque_ncm": [30],
     "cad_cam": True, "indication": "Esthetic zirconia abutment for anterior."},
    {"type": "final_abutment", "subtype": "ZioCera Angled Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "angulation_deg": [15, 25],
     "material": ["zirconia"], "torque_ncm": [30]},
    {"type": "final_abutment", "subtype": "Angled Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "angulation_deg": [15, 25],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "ti_base", "subtype": "TS Ti-Base for Crown",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "cad_cam": True,
     "torque_ncm": [30]},
    {"type": "scanbody", "subtype": "TS Scan Body",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["PEEK", "titanium_alloy"]},
    {"type": "impression_coping", "subtype": "Open Tray Impression Coping",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"]},
    {"type": "impression_coping", "subtype": "Closed Tray Impression Coping",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"]},
    {"type": "analog", "subtype": "Lab Analog",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["stainless_steel"]},
    {"type": "prosthetic_screw", "subtype": "Abutment Screw",
     "platforms_mm": [3.5, 4.5, 5.5], "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Straight",
     "platforms_mm": [4.5, 5.5], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Angled 17°",
     "platforms_mm": [4.5, 5.5], "gingival_heights_mm": [2, 3, 4, 5],
     "angulation_deg": [17], "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Angled 30°",
     "platforms_mm": [4.5, 5.5], "gingival_heights_mm": [2, 3, 4, 5],
     "angulation_deg": [30], "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "overdenture_attachment", "subtype": "Locator Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "retention": ["nylon_male"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Abutment",
     "platforms_mm": [3.5, 4.5, 5.5], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
]

OSSTEM_OCTA_COMPONENTS: List[Dict[str, Any]] = [
    {"type": "final_abutment", "subtype": "Solid Abutment (cement-retained)",
     "material": ["titanium_alloy"], "torque_ncm": [35], "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "Excellent Solid",
     "material": ["titanium_alloy"], "torque_ncm": [35], "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "ComOcta",
     "material": ["titanium_alloy"], "torque_ncm": [35], "retention": ["cement", "screw"]},
    {"type": "final_abutment", "subtype": "ComOcta Plus",
     "material": ["titanium_alloy"], "torque_ncm": [35]},
    {"type": "ti_base", "subtype": "ComOcta Milling",
     "material": ["titanium_alloy"], "torque_ncm": [35], "cad_cam": True,
     "indication": "CAD/CAM milling block for SS III prosthetic platform."},
    {"type": "final_abutment", "subtype": "ComOcta Angled",
     "angulation_deg": [15, 25], "material": ["titanium_alloy"], "torque_ncm": [35]},
    {"type": "healing_abutment", "subtype": "Healing Abutment",
     "gingival_heights_mm": [3, 4, 5, 7], "material": ["titanium_alloy"], "torque_ncm": [15]},
    {"type": "scanbody", "subtype": "SS Scan Body",
     "material": ["PEEK", "titanium_alloy"]},
    {"type": "analog", "subtype": "Lab Analog", "material": ["stainless_steel"]},
]

OSSTEM_MS_COMPONENTS: List[Dict[str, Any]] = [
    {"type": "overdenture_attachment", "subtype": "Ball Head (1-piece, integral to implant)",
     "material": ["titanium_alloy"], "retention": ["o_ring", "locator_male"]},
    {"type": "overdenture_attachment", "subtype": "Locator Cap Adapter",
     "material": ["titanium_alloy"], "retention": ["locator_male"],
     "indication": "Compatible with standard Locator denture housings."},
    {"type": "overdenture_attachment", "subtype": "O-Ring Housing",
     "material": ["stainless_steel", "rubber"]},
]

# ───────────── MIS LANCE+ full prosthetic suite ─────────────
MIS_LANCE_COMPONENTS: List[Dict[str, Any]] = [
    {"type": "cover_screw", "subtype": "Implant Cover Screw",
     "platforms_mm": [3.30, 3.75, 4.20, 5.0], "material": ["titanium_alloy"],
     "retention": ["screw"]},
    {"type": "healing_abutment", "subtype": "Healing Cap — Narrow",
     "platforms_mm": [3.30], "gingival_heights_mm": [2, 3, 4, 6, 8],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Concave Healing Cap — Narrow",
     "platforms_mm": [3.30], "gingival_heights_mm": [2, 3, 4, 5, 6],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Anatomic Healing Cap — Narrow",
     "platforms_mm": [3.30], "gingival_heights_mm": [2, 3, 4, 5, 6],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Healing Cap — Standard",
     "platforms_mm": [3.75], "gingival_heights_mm": [2, 3, 4, 5, 6, 8],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Healing Cap — Standard Ø4.8",
     "platforms_mm": [3.75], "gingival_heights_mm": [3, 4, 5, 6],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Concave Healing Cap — Standard",
     "platforms_mm": [3.75], "gingival_heights_mm": [2, 3, 4],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Anatomic Healing Cap — Standard",
     "platforms_mm": [3.75], "gingival_heights_mm": [3, 4, 5, 6],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Healing Cap — Wide",
     "platforms_mm": [5.0], "gingival_heights_mm": [2, 3, 4, 5, 6, 8],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Concave Healing Cap — Wide",
     "platforms_mm": [5.0], "gingival_heights_mm": [2, 3, 4],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "healing_abutment", "subtype": "Anatomic Healing Cap — Wide",
     "platforms_mm": [5.0], "gingival_heights_mm": [3, 4, 5],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Narrow Temp Plastic Abutment",
     "platforms_mm": [3.30], "material": ["plastic"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Temp Plastic Abutment",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["plastic"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Direct Temp Plastic Cylinder (Free / Anti-rotation, Standard or Concave)",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["plastic"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Direct Gold Plastic Cylinder (Free / Anti-rotation)",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["gold_alloy", "plastic"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Direct CoCr Plastic Cylinder (Free / Anti-rotation)",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["CoCr", "plastic"], "torque_ncm": [20, 25]},
    {"type": "temporary_cylinder", "subtype": "Wide Profile Direct Plastic Cylinder (Free / Anti-rotation)",
     "platforms_mm": [3.75, 5.0], "material": ["plastic"], "torque_ncm": [20, 25]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Narrow Straight",
     "platforms_mm": [3.30], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Standard Straight",
     "platforms_mm": [3.75], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Wide Straight",
     "platforms_mm": [5.0], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Angled 17°",
     "platforms_mm": [3.75, 5.0], "gingival_heights_mm": [3, 4],
     "angulation_deg": [17], "material": ["titanium_alloy"], "torque_ncm": [20]},
    {"type": "multi_unit_abutment", "subtype": "MUA — Angled 30°",
     "platforms_mm": [3.75, 5.0], "gingival_heights_mm": [4, 5],
     "angulation_deg": [30], "material": ["titanium_alloy"], "torque_ncm": [20]},
    {"type": "final_abutment", "subtype": "Cementable Abutment — Narrow (Straight + 20°)",
     "platforms_mm": [3.30], "gingival_heights_mm": [6.4, 7.3], "angulation_deg": [0, 20],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "Cementable Abutment — Standard (Straight + 15°, optional Concave)",
     "platforms_mm": [3.75], "gingival_heights_mm": [6.6, 7, 7.5, 8],
     "angulation_deg": [0, 15], "material": ["titanium_alloy"], "torque_ncm": [30],
     "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "Cementable Abutment — Wide",
     "platforms_mm": [5.0], "gingival_heights_mm": [8],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["cement"]},
    {"type": "final_abutment", "subtype": "CPK Transgingival Abutment (N/S/W, Straight or Concave)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [3, 4, 6],
     "material": ["titanium_alloy"], "torque_ncm": [30], "retention": ["cement"],
     "indication": "Transgingival concept; one-piece, no separate healing phase."},
    {"type": "ti_base", "subtype": "EZ-Base System",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [1.5, 5],
     "material": ["titanium_alloy"], "torque_ncm": [25], "cad_cam": True},
    {"type": "ti_base", "subtype": "Ti-Base — Anti-rotation",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [1.5, 4],
     "material": ["titanium_alloy"], "torque_ncm": [30], "cad_cam": True,
     "retention": ["screw"]},
    {"type": "ti_base", "subtype": "Ti-Base — Free Rotation (bridge / non-engaging)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [1.5, 4],
     "material": ["titanium_alloy"], "torque_ncm": [30], "cad_cam": True,
     "retention": ["screw"]},
    {"type": "ti_base", "subtype": "Incisor Esthetic Ti Abutment",
     "platforms_mm": [3.30, 3.75], "gingival_heights_mm": [0.5, 6],
     "material": ["titanium_alloy"], "torque_ncm": [30], "cad_cam": True},
    {"type": "scanbody", "subtype": "Scan Post (Narrow / Standard / Wide / MUA)",
     "platforms_mm": [3.30, 3.75, 5.0, 4.80], "gingival_heights_mm": [10],
     "material": ["titanium_alloy"], "torque_ncm": [30]},
    {"type": "impression_coping", "subtype": "Impression Coping — Closed Tray (N/S/W)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [9],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "impression_coping", "subtype": "Direct Impression Coping — Closed Tray (Standard or Concave)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [2, 6],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "impression_coping", "subtype": "Direct Impression Coping — Open Tray (Standard or Concave)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [11],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "impression_coping", "subtype": "Direct Press-Fit, Closed Tray",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [11],
     "material": ["titanium_alloy"], "torque_ncm": [20, 25]},
    {"type": "analog", "subtype": "Implant Analog (N/S/W)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [12],
     "material": ["stainless_steel"]},
    {"type": "analog", "subtype": "Digital Model Analog (N/S/W/MUA)",
     "platforms_mm": [3.30, 3.75, 4.80, 5.0], "gingival_heights_mm": [10],
     "material": ["stainless_steel"], "torque_ncm": [15]},
    {"type": "analog", "subtype": "Milling Analog (N/S/W)",
     "platforms_mm": [3.30, 3.75, 5.0], "gingival_heights_mm": [13.5],
     "material": ["stainless_steel"], "torque_ncm": [30]},
    {"type": "analog", "subtype": "OT-Equator Components Analog",
     "platforms_mm": [4.0, 5.0], "material": ["stainless_steel"]},
    {"type": "analog", "subtype": "Ball Attachment System Analog",
     "platforms_mm": [4.0, 5.0], "material": ["stainless_steel"], "torque_ncm": [30]},
    {"type": "analog", "subtype": "LOCKIT System Analog",
     "platforms_mm": [3.75, 4.5], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["stainless_steel"], "torque_ncm": [30]},
    {"type": "analog", "subtype": "CPK Kit Analog",
     "platforms_mm": [4.8, 5.5], "gingival_heights_mm": [1, 2, 3, 4],
     "material": ["stainless_steel"]},
    {"type": "prosthetic_screw", "subtype": "Mini Prosthetic Screw",
     "platforms_mm": [3.30], "material": ["titanium_alloy"], "torque_ncm": [20, 30]},
    {"type": "prosthetic_screw", "subtype": "Direct Prosthetic Screw",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["titanium_alloy"], "torque_ncm": [20, 30]},
    {"type": "prosthetic_screw", "subtype": "Medium Prosthetic Screw",
     "platforms_mm": [3.75], "material": ["titanium_alloy"], "torque_ncm": [20, 30]},
    {"type": "prosthetic_screw", "subtype": "Long Prosthetic Screw",
     "platforms_mm": [3.75], "material": ["titanium_alloy"], "torque_ncm": [20, 30]},
    {"type": "prosthetic_screw", "subtype": "Direct Gold Prosthetic Screw",
     "platforms_mm": [3.75], "material": ["gold_alloy"], "torque_ncm": [20, 30]},
    {"type": "prosthetic_screw", "subtype": "EZ-Base Prosthetic Screw",
     "platforms_mm": [3.30, 3.75, 5.0], "material": ["titanium_alloy"], "torque_ncm": [25]},
    {"type": "overdenture_attachment", "subtype": "Ball Attachment — Narrow",
     "platforms_mm": [3.30], "gingival_heights_mm": [2, 3, 4],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Attachment — Standard",
     "platforms_mm": [3.75], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Attachment — Standard Angled 15°",
     "platforms_mm": [3.75], "gingival_heights_mm": [3.5], "angulation_deg": [15],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Attachment — Standard Angled 25°",
     "platforms_mm": [3.75], "gingival_heights_mm": [3.5], "angulation_deg": [25],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "Ball Attachment — Wide",
     "platforms_mm": [5.0], "gingival_heights_mm": [1, 3, 5],
     "material": ["titanium_alloy"], "retention": ["o_ring"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "LOCKIT Abutment — N/S",
     "platforms_mm": [3.75], "gingival_heights_mm": [1, 2, 3, 4, 5],
     "material": ["titanium_alloy"], "retention": ["nylon_male"], "torque_ncm": [30]},
    {"type": "overdenture_attachment", "subtype": "LOCKIT Abutment — Wide",
     "platforms_mm": [4.5], "gingival_heights_mm": [1, 3, 5],
     "material": ["titanium_alloy"], "retention": ["nylon_male"], "torque_ncm": [30]},
]

MIS_LANCE_FEATURES: List[str] = [
    "Conical, root-shaped geometry",
    "Variable thread design for excellent primary stability",
    "Triple thread geometry for increased insertion rate (2.25 mm/rotation)",
    "Platform-switching design concept for crestal bone preservation",
    "Sand-blasted + acid-etched (SBA) surface for effective osseointegration",
    "Internal hex prosthetic platforms: Ø3.30 (Narrow), Ø3.75 (Standard), Ø4.20, Ø5.0 (Wide)",
]

MIS_LANCE_NOTES: str = (
    "MIS LANCE+ uses an internal hex connection across 4 platforms (Narrow Ø3.30, "
    "Standard Ø3.75, Ø4.20, Wide Ø5.0). Three platform-switched healing-cap profiles "
    "(Standard, Concave, Anatomic). Multi-Unit compatible (Ø4.80 MUA platform). "
    "LOCKIT (Locator-style) and Ball overdenture attachments available."
)


def apply_iter162_overrides(
    osstem_tsiii: Dict[str, Any],
    osstem_tsiv: Dict[str, Any],
    osstem_ssiii: Dict[str, Any],
    osstem_ms: Dict[str, Any],
    osstem_etiii_nh: Dict[str, Any],
    mis_lance_plus: Dict[str, Any],
    cowell_inno_internal: Dict[str, Any],
    cowell_inno_external: Dict[str, Any],
) -> None:
    """Mutates the passed curated dicts to use the rich iter-162 component data
    (PDF-extracted catalogs from Cowellmedi, Osstem and MIS). Called by
    `implant_catalog_seed.py` immediately after the base records are defined,
    so the startup seeder picks up the rich data on every restart."""
    osstem_tsiii["components"] = list(OSSTEM_INTERNAL_HEX_COMPONENTS)
    osstem_tsiv["components"] = list(OSSTEM_INTERNAL_HEX_COMPONENTS)
    osstem_etiii_nh["components"] = list(OSSTEM_INTERNAL_HEX_COMPONENTS)
    osstem_ssiii["components"] = list(OSSTEM_OCTA_COMPONENTS)
    osstem_ms["components"] = list(OSSTEM_MS_COMPONENTS)

    mis_lance_plus["components"] = list(MIS_LANCE_COMPONENTS)
    mis_lance_plus["features"] = list(MIS_LANCE_FEATURES)
    mis_lance_plus["compatibility_notes"] = MIS_LANCE_NOTES
    mis_lance_plus["implant"] = {
        "diameters_mm": [3.30, 3.75, 4.20, 5.0],
        "lengths_mm": [8, 10, 11.5, 13, 16],
        "bone_types": ["soft (3 & 4)", "hard (1 & 2)"],
        "healing_modes": ["submerged", "non_submerged"],
    }

    cowell_inno_internal["components"] = list(COWELL_COMPONENTS)
    cowell_inno_external["components"] = list(COWELL_COMPONENTS)
