"""
Straumann BLT — RC (Regular CrossFit, Ø 4.1 / Ø 4.8 mm) prosthetic catalog
(iter-304, Feb 2026)

Source: user-uploaded "Straumann RC Prosthetic Components" PDF.

The same RC platform is shared by both Ø 4.1 mm and Ø 4.8 mm BLT implants,
so this single catalog backs both diameters in the Platform-dropdown UI
(`RC 4.1 mm` and `RC 4.8 mm` options both resolve to `platform: "RC"`).

Workflow-level split (impression posts / analogs / scan bodies)
───────────────────────────────────────────────────────────────
Mirrors iter-303 NC schema:
  workflow_level: "implant" — direct on implant connection
  workflow_level: "abutment" — on SRA / multi-base
The printed subtype text also calls out the level explicitly for the
existing card UI.

REF accuracy
────────────
Most REFs verbatim from the PDF.  A handful (long-form Cementable
Abutments where the OCR returned duplicate REFs for clearly different
SKUs) carry `ref_to_verify: true` for admin correction.
"""

from typing import Dict, List
import copy


RC_COMPONENTS: List[Dict] = [
    # ── HEALING ABUTMENTS (conical Ø4.8 + bottle Ø4.4/4.7 + customizable) ──
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 4.8 — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.8, "gingival_heights_mm": [2.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42225", "indication": "Soft-tissue conditioning on RC (Ø 4.1/4.8 mm) implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 4.8 — GH 4 mm",
     "platform": "RC", "diameter_mm": 4.8, "gingival_heights_mm": [4.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42245", "indication": "Soft-tissue conditioning on RC implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 6 — GH 5 mm",
     "platform": "RC", "diameter_mm": 6.0, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42425", "indication": "Wider emergence healing abutment for RC implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 5 — GH 5 mm",
     "platform": "RC", "diameter_mm": 5.0, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42445", "indication": "Standard healing abutment for RC implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 6.5 — GH 6.5 mm",
     "platform": "RC", "diameter_mm": 6.5, "gingival_heights_mm": [6.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42465", "indication": "Wider emergence healing abutment — deep ridge"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, bottle-shaped Ø 4.4/4.7 — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [3.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42265", "indication": "Bottle-shaped healing abutment for tight emergence"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, bottle-shaped Ø 4.4/4.7 — GH 4 mm",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [4.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42345", "indication": "Bottle-shaped healing abutment for tight emergence"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, bottle-shaped Ø 4.4/4.7 — GH 5 mm",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42365", "indication": "Bottle-shaped healing abutment — deeper ridge"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, customizable Ø 7 — GH 7 mm",
     "platform": "RC", "diameter_mm": 7.0, "gingival_heights_mm": [7.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.42705", "indication": "Customizable healing abutment — chair-side profile shaping"},

    # ── IMPRESSION POSTS — LEVEL A (IMPLANT-LEVEL) ──────────────────
    {"type": "impression_post", "subtype": "Implant-level — closed tray, engaging (short)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.4202",
     "indication": "Closed-tray transfer with anti-rotation, short body"},
    {"type": "impression_post", "subtype": "Implant-level — closed tray, engaging (long)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.4205",
     "indication": "Closed-tray transfer with anti-rotation, long body"},
    {"type": "impression_post", "subtype": "Implant-level — closed tray, non-engaging (short)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.0060",
     "indication": "Closed-tray transfer, rotational — short body"},
    {"type": "impression_post", "subtype": "Implant-level — closed tray, non-engaging (long)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.0061",
     "indication": "Closed-tray transfer, rotational — long body"},
    {"type": "impression_post", "subtype": "Implant-level — open tray (Crown)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.2244",
     "indication": "Open-tray transfer for single crowns — splinted technique"},
    {"type": "impression_post", "subtype": "Implant-level — open tray (Bridge / Bar)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0012",
     "indication": "Open-tray transfer for bridges / bars — splinted technique"},
    {"type": "impression_post", "subtype": "Implant-level — open tray (edentulous)",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0008",
     "indication": "Open-tray transfer for edentulous full-arch cases"},

    # ── IMPRESSION POSTS — LEVEL B (ABUTMENT / SRA-LEVEL) ──────────
    {"type": "impression_post", "subtype": "Abutment-level — open tray (Crown, SRA Ø 4.6)",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.2246",
     "indication": "Open-tray transfer onto Ø 4.6 mm SRA shoulder — single crown"},
    {"type": "impression_post", "subtype": "Abutment-level — open tray (Bridge / Bar, SRA Ø 4.6)",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0014",
     "indication": "Open-tray transfer onto Ø 4.6 mm SRA shoulder — bridge / bar"},

    # ── LAB ANALOGS — LEVEL A (IMPLANT-LEVEL) ──────────────────────
    {"type": "implant_analog", "subtype": "Implant-level Analog — closed tray",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.4201",
     "indication": "Laboratory analog for implant-level closed-tray transfer"},
    {"type": "implant_analog", "subtype": "Implant-level Analog — open tray",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.4101",
     "indication": "Laboratory analog for implant-level open-tray transfer"},

    # ── LAB ANALOGS — LEVEL B (ABUTMENT / SRA-LEVEL) ───────────────
    {"type": "implant_analog", "subtype": "Abutment-level Analog — Crown (SRA Ø 4.6)",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.2244", "ref_to_verify": True,
     "indication": "Analog mirroring Ø 4.6 mm SRA shoulder — single crown model"},
    {"type": "implant_analog", "subtype": "Abutment-level Analog — Bridge / Bar (SRA Ø 4.6)",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.0010", "ref_to_verify": True,
     "indication": "Analog mirroring Ø 4.6 mm SRA shoulder — bridge / bar model"},

    # ── SCAN BODIES — LEVEL A & LEVEL B ────────────────────────────
    {"type": "scan_body", "subtype": "Implant-level — CARES® Mono-Scanbody",
     "platform": "RC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["PEEK"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.4915",
     "indication": "Digital scan body for implant-level CAD/CAM workflow"},
    {"type": "scan_body", "subtype": "Abutment-level (SRA Ø 4.6) — CARES® Scanbody for SRA",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["PEEK"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0001",
     "indication": "Digital scan body for Ø 4.6 mm SRA shoulder"},

    # ── TEMPORARY ABUTMENTS ────────────────────────────────────────
    {"type": "temporary_abutment", "subtype": "Temporary Abutment, TAN — Crown",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.4371", "indication": "Immediate / interim single-crown temporization"},
    {"type": "temporary_abutment", "subtype": "Temporary Abutment, TAN — Bridge",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.4375", "indication": "Immediate / interim bridge temporization"},
    {"type": "temporary_abutment", "subtype": "Temporary Abutment, TAN/PMMA",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN", "PMMA"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.4372", "indication": "TAN/PMMA temporary abutment for chair-side temporization"},

    # ── ANATOMIC ABUTMENTS (cementable, straight + 15°) ────────────
    {"type": "final_abutment", "subtype": "Anatomic Abutment — straight (0°) — GH 2 mm",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4102", "indication": "Cement-retained single crown — anatomic emergence"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — straight (0°) — GH 3.5 mm",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4104", "indication": "Cement-retained single crown — anatomic emergence"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — angled 15° — GH 2 mm",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4152", "indication": "Cement-retained crown — 15° axis correction"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — angled 15° — GH 3.5 mm",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [3.5], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4154", "indication": "Cement-retained crown — 15° axis correction"},

    # ── CEMENTABLE ABUTMENTS — straight, Ø 3.5 shoulder ────────────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 1 mm",
     "platform": "RC", "diameter_mm": 3.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4321", "indication": "Cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 2 mm",
     "platform": "RC", "diameter_mm": 3.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4322", "indication": "Cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 3 mm",
     "platform": "RC", "diameter_mm": 3.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4323", "indication": "Cementable abutment for crown / bridge"},
    # ── Cementable Ø 4.6 shoulder ──────────────────────────────────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 1 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4331", "indication": "Wider cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4332", "indication": "Wider cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4333", "indication": "Wider cementable abutment for crown / bridge"},
    # ── Cementable Ø 5.5 shoulder ──────────────────────────────────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 5.5 — straight — GH 1 mm",
     "platform": "RC", "diameter_mm": 5.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4325", "indication": "Wider cementable abutment, Ø 5.5 — crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 5.5 — straight — GH 2 mm",
     "platform": "RC", "diameter_mm": 5.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4326", "indication": "Wider cementable abutment, Ø 5.5 — crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 5.5 — straight — GH 3 mm",
     "platform": "RC", "diameter_mm": 5.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4327", "indication": "Wider cementable abutment, Ø 5.5 — crown / bridge"},
    # ── Cementable Ø 6.5 shoulder ──────────────────────────────────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 6.5 — straight — GH 1 mm",
     "platform": "RC", "diameter_mm": 6.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4335", "indication": "Wider cementable abutment, Ø 6.5 — crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 6.5 — straight — GH 2 mm",
     "platform": "RC", "diameter_mm": 6.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4336", "indication": "Wider cementable abutment, Ø 6.5 — crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 6.5 — straight — GH 3 mm",
     "platform": "RC", "diameter_mm": 6.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.4337", "indication": "Wider cementable abutment, Ø 6.5 — crown / bridge"},

    # ── VARIOBASE FOR CROWN — straight + angled 17° + AS 25° ────────
    {"type": "variobase_crown", "subtype": "Variobase® for Crown, Ø 4.5 — straight",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0026", "indication": "Ti-base for cement- or screw-retained single crown"},
    {"type": "variobase_crown", "subtype": "Variobase® C, Ø 4.5 — GH 1 mm",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0044", "indication": "Variobase Crown — GH 1 mm"},
    {"type": "variobase_crown", "subtype": "Variobase® C, Ø 4.5 — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0103", "indication": "Variobase Crown — GH 2 mm"},
    {"type": "variobase_crown", "subtype": "Variobase® C, Ø 4.5 — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0105", "indication": "Variobase Crown — GH 3 mm"},
    {"type": "variobase_crown", "subtype": "Variobase® C (high), Ø 4.5 — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0107", "indication": "Variobase Crown (high profile) — GH 2 mm"},
    {"type": "variobase_crown", "subtype": "Variobase® C (high), Ø 4.5 — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0109", "indication": "Variobase Crown (high profile) — GH 3 mm"},
    {"type": "variobase_crown", "subtype": "Variobase® for Crown AS 25°, Ø 4.7",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [], "angulation_deg": 25,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.0087", "indication": "Angled-screw Ti-base — palatal screw access, 25°"},

    # ── VARIOBASE FOR BRIDGE / BAR (cylindrical) ───────────────────
    {"type": "variobase_bridge", "subtype": "Variobase® for Bridge / Bar, cylindrical — AH 3.5",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [3.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.0096", "indication": "Cylindrical Ti-base for multi-unit bridge or bar"},
    {"type": "variobase_bridge", "subtype": "Variobase® for Bridge / Bar, cylindrical — AH 5.5",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [5.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.0111", "indication": "Cylindrical Ti-base for multi-unit bridge or bar — deep ridge"},

    # ── VARIOBASE CYLINDRICAL FOR SRA (level-B Ti-base) ────────────
    {"type": "variobase_bridge", "subtype": "Variobase Cylindrical for SRA — Ø 4.6",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "023.0032", "indication": "Ti-base mounting onto Ø 4.6 mm SRA shoulder"},

    # ── SCREW-RETAINED ABUTMENTS (SRA / Multi-Base) ────────────────
    # Straight 0°
    {"type": "screw_retained_abutment", "subtype": "SRA — straight (0°) — GH 1.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [1.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01325", "indication": "Multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA — straight (0°) — GH 2.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01335", "indication": "Multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA — straight (0°) — GH 3.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01345", "indication": "Multi-unit screw-retained abutment, straight"},
    # Angled 17° Type A (anti-rotation, single-unit)
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 1.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [1.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01505", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 2.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01525", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 3.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01545", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 4.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [4.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01565", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 5.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [5.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01585", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 6.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [6.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01605", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type A — GH 7.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [7.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01625", "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    # Angled 17° Type B (rotational, multi-unit splinted)
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 1.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [1.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01515", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 2.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01535", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 3.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01555", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 4.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [4.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01575", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 5.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [5.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01595", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 6.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [6.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01615", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA — angled 17° Type B — GH 7.5 mm",
     "platform": "RC", "diameter_mm": 4.6, "gingival_heights_mm": [7.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01635", "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},

    # ── BURN-OUT COPINGS ───────────────────────────────────────────
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Cementable Abutments — Crown",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [5.0],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4326", "indication": "Burn-out coping for cast crown on cementable abutment"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Cementable Abutments — Bridge",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [5.0],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4320", "indication": "Burn-out coping for cast bridge on cementable abutment"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown AS — AH 3.5",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [3.5], "angulation_deg": 25,
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4759", "indication": "Burn-out for angled-screw Variobase AS — short"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown AS — AH 5.5",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [5.5], "angulation_deg": 25,
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0017", "indication": "Burn-out for angled-screw Variobase AS — tall"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown AS — AH 3.5 (V4 pack)",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [3.5], "angulation_deg": 25,
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4759-04", "indication": "Burn-out for angled-screw Variobase AS — 4-piece refill"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown AS — AH 5.5 (V4 pack)",
     "platform": "RC", "diameter_mm": 4.7, "gingival_heights_mm": [5.5], "angulation_deg": 25,
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0017V4", "indication": "Burn-out for angled-screw Variobase AS — 4-piece refill"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Bridge/Bar Cylindrical",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0026", "indication": "Burn-out for cylindrical bridge/bar Variobase"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Bridge/Bar Cylindrical (tall)",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0030", "indication": "Burn-out for cylindrical bridge/bar Variobase — tall"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Bridge/Bar (V4 pack)",
     "platform": "RC", "diameter_mm": 4.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0030V4", "indication": "Burn-out for cylindrical bridge/bar Variobase — refill"},
    {"type": "burnout_coping", "subtype": "Cylindrical Burn-out for SRA — Ø 4.6",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0032", "indication": "Burn-out for cylindrical SRA-level Ti-base — Ø 4.6"},
    {"type": "burnout_coping", "subtype": "Cylindrical Burn-out for SRA — Ø 4.6 (V4 pack)",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0032V4", "indication": "Burn-out cylindrical SRA — 4-piece refill"},

    # ── GOLD COPINGS ───────────────────────────────────────────────
    {"type": "gold_coping", "subtype": "Gold Coping — Crown",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Gold"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4754", "indication": "Gold coping for crown casting on SRA"},
    {"type": "gold_coping", "subtype": "Gold Coping — Bridge",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Gold"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4758", "indication": "Gold coping for bridge casting on SRA"},

    # ── TITANIUM COPINGS — FINAL ───────────────────────────────────
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Crown",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4747", "indication": "Final titanium coping — single crown on SRA"},
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Bridge",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4751", "indication": "Final titanium coping — bridge on SRA"},
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Bar",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4752", "indication": "Final titanium coping — bar on SRA"},
    # TEMPORARY
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Crown",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0023", "indication": "Temporary titanium coping — single crown on SRA"},
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Bridge",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0024", "indication": "Temporary titanium coping — bridge on SRA"},

    # ── PROSTHETIC / LAB SCREWS ────────────────────────────────────
    {"type": "prosthetic_screw", "subtype": "Basal Screw — RC (for Anatomic / Cementable Abutments)",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "025.4900",
     "indication": "Basal screw for anatomic / cementable abutments"},
    {"type": "prosthetic_screw", "subtype": "Basal Screw — RC (for Cementable Abutments, alt)",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "025.4908",
     "indication": "Alternate basal screw for cementable abutments"},
    {"type": "prosthetic_screw", "subtype": "Basal Screw — RC (for Variobase / SRA)",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "025.2926",
     "indication": "Basal screw for Variobase / SRA cylindrical"},
    {"type": "prosthetic_screw", "subtype": "Occlusal Screw — RC",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "023.4763",
     "indication": "Occlusal screw for gold / titanium copings"},
    {"type": "prosthetic_screw", "subtype": "Lab Processing Screw — RC (L 20 mm)",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0006",
     "indication": "Long lab-processing screw for try-in / framework verification"},
    {"type": "prosthetic_screw", "subtype": "Lab Processing Screw — RC (L 10 mm)",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0052",
     "indication": "Short lab-processing screw for try-in / framework verification"},

    # ── PROTECTIVE CAPS for SRA ────────────────────────────────────
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — GH 5.0 mm",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [5.0],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0020-04",
     "indication": "Protects RC SRA between sessions — 5 mm"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — GH 5.1 mm",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [5.1],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.4323-04",
     "indication": "Protects RC SRA between sessions — 5.1 mm"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — GH 6.6 mm",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [6.6],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.4324-04",
     "indication": "Protects RC SRA between sessions — 6.6 mm (deep ridge)"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — GH 8.1 mm",
     "platform": "RC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [8.1],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.4325-04",
     "indication": "Protects RC SRA between sessions — 8.1 mm (very deep ridge)"},

    # ── PRE-MILLED ABUTMENT BLANKS (Medentika holder) ──────────────
    {"type": "premilled_blank", "subtype": "Pre-milled Abutment Blank, for Medentika Holder",
     "platform": "RC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "022.0031",
     "indication": "Custom-milled abutment blank (Medentika holder)"},

    # ── NOVALOC® ABUTMENTS (iter-305) — overdenture retention ──────
    # ADLC-coated titanium abutments for retentive (snap-on) removable
    # overdentures.  15° variants combine with the Novaloc retentive
    # cap to deliver up to 20° of total path-of-insertion correction.
    # RC 0° — GH 1 / 2 / 3 / 4 / 5 / 6 mm  (REF 022.0052 – 022.0057)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 1 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0052", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0053", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0054", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 4 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0055", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 5 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0056", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 6 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0057", "indication": "Snap-on overdenture retention — straight, deep ridge"},
    # RC 15° Type A — GH 2 / 3 / 4 / 5 / 6 mm  (REF 022.0067 – 022.0071)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0067",
     "indication": "Angled Novaloc 15° Type A — anti-rotation, single overdenture attachment (up to 20° path-of-insertion correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0068",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 4 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0069",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 5 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0070",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 6 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0071",
     "indication": "Angled Novaloc 15° Type A — anti-rotation, deep ridge (up to 20° path correction)"},
    # RC 15° Type B — GH 2 / 3 / 4 / 5 / 6 mm  (REF 022.0077 – 022.0081)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 2 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0077",
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 3 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0078",
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 4 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0079", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 5 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0080", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 6 mm",
     "platform": "RC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0081", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture, deep ridge"},
]


# Three BLT systems share the same RC prosthetic stack.
SYSTEMS_USING_RC: List[str] = [
    "BLT Roxolid SLActive",
    "BLT Roxolid SLA",
    "BLT Ti SLA",
]


def expanded_rc_components_for(system_name: str) -> List[Dict]:
    """Return a deep copy of the RC component list for the given BLT
    system. Returns [] for systems outside this batch."""
    if system_name not in SYSTEMS_USING_RC:
        return []
    return copy.deepcopy(RC_COMPONENTS)
