"""
Straumann BLT — NC (Ø 3.3 mm, Narrow CrossFit) prosthetic-component catalog
(iter-303, Feb 2026)

Source: user-uploaded "Straumann NC Prosthetic Components" PDF.

Scope
─────
Adds the full NC prosthetic stack to the same 3 BLT implant systems that
share the prosthetic catalog (BLT Roxolid SLActive / BLT Roxolid SLA /
BLT Ti SLA).  Sits alongside the iter-301 SC list with no overwrite.

Workflow-level field
────────────────────
Several categories (impression posts, lab analogs, scan bodies) come in
TWO levels per Straumann's catalog:

  • Level A — IMPLANT-LEVEL  →  component seats directly on the implant
                                connection.
  • Level B — ABUTMENT-LEVEL →  component seats on a screw-retained
                                abutment (SRA / multi-base) that has
                                already been torqued onto the implant.

To avoid fragmenting the existing `type` chip in the Compare UI, the
discriminator is stored as `workflow_level: "implant" | "abutment"` on
the same `impression_post` / `implant_analog` / `scan_body` types. The
printed subtype also calls it out explicitly ("Implant-level — closed
tray, engaging", etc.) so it's visible in the card UI today.

REF accuracy
────────────
Most REFs are reproduced verbatim from the PDF.  A handful (open-tray
"long" variants, a few abutment-level analogs) had OCR collisions in
the source document — those carry `ref_to_verify: true` so an admin
can correct them through the catalog editor without code changes.
"""

from typing import Dict, List
import copy


# ─────────────────────────────────────────────────────────────────────
# NC (Ø 3.3 mm) component catalog
# ─────────────────────────────────────────────────────────────────────
NC_COMPONENTS: List[Dict] = [
    # ── HEALING ABUTMENTS — conical Ø 3.6, conical Ø 4.8, bottle Ø 3.3,
    #    customizable Ø 5.0 ────────────────────────────────────────────
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 3.6 — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 3.6, "gingival_heights_mm": [3.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22225", "indication": "Soft-tissue conditioning on NC (Ø 3.3 mm) implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 3.6 — GH 5 mm",
     "platform": "NC", "diameter_mm": 3.6, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22245", "indication": "Soft-tissue conditioning on NC (Ø 3.3 mm) implants"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 3.6 — GH 7 mm",
     "platform": "NC", "diameter_mm": 3.6, "gingival_heights_mm": [7.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22265", "indication": "Soft-tissue conditioning on NC (Ø 3.3 mm) implants — deep ridge"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 4.8 — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 4.8, "gingival_heights_mm": [3.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22425", "indication": "Wider emergence-profile healing abutment for NC"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 4.8 — GH 5 mm",
     "platform": "NC", "diameter_mm": 4.8, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22445", "indication": "Wider emergence-profile healing abutment for NC"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, conical Ø 4.8 — GH 7 mm",
     "platform": "NC", "diameter_mm": 4.8, "gingival_heights_mm": [7.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22465", "indication": "Wider emergence-profile healing abutment for NC — deep ridge"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, bottle-shaped Ø 3.3 — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 3.3, "gingival_heights_mm": [3.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22345", "indication": "Bottle-shaped healing abutment for tight emergence"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, bottle-shaped Ø 3.3 — GH 5 mm",
     "platform": "NC", "diameter_mm": 3.3, "gingival_heights_mm": [5.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22365", "indication": "Bottle-shaped healing abutment for tight emergence"},
    {"type": "healing_abutment", "subtype": "Healing Abutment, customizable Ø 5.0 — GH 7 mm",
     "platform": "NC", "diameter_mm": 5.0, "gingival_heights_mm": [7.0],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.22705", "indication": "Customizable healing abutment (chair-side profile shaping)"},

    # ── IMPRESSION POSTS — LEVEL A (IMPLANT-LEVEL) ──────────────────
    {"type": "impression_post",
     "subtype": "Implant-level — closed tray, non-engaging (short)",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.2201",
     "indication": "Closed-tray implant-level transfer — short body"},
    {"type": "impression_post",
     "subtype": "Implant-level — closed tray, engaging",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.2202",
     "indication": "Closed-tray implant-level transfer — anti-rotation (engaging) for single units"},
    {"type": "impression_post",
     "subtype": "Implant-level — closed tray, non-engaging (long)",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.2205",
     "indication": "Closed-tray implant-level transfer — long body for deeper implants"},
    {"type": "impression_post",
     "subtype": "Implant-level — open tray (short)",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0058",
     "indication": "Open-tray implant-level transfer — short body, splinted technique"},
    {"type": "impression_post",
     "subtype": "Implant-level — open tray (long)",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0059", "ref_to_verify": True,
     "indication": "Open-tray implant-level transfer — long body"},

    # ── IMPRESSION POSTS — LEVEL B (ABUTMENT / SRA-LEVEL) ──────────
    {"type": "impression_post",
     "subtype": "Abutment-level (SRA Ø 3.5) — closed tray",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.2245",
     "indication": "Closed-tray transfer onto Ø 3.5 mm SRA shoulder"},
    {"type": "impression_post",
     "subtype": "Abutment-level (SRA Ø 4.6) — closed tray",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["snap"], "torque_ncm": None,
     "catalog_code": "025.2246",
     "indication": "Closed-tray transfer onto Ø 4.6 mm SRA shoulder"},
    {"type": "impression_post",
     "subtype": "Abutment-level (SRA Ø 3.5) — open tray",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0013",
     "indication": "Open-tray transfer onto Ø 3.5 mm SRA shoulder — splinted technique"},
    {"type": "impression_post",
     "subtype": "Abutment-level (SRA Ø 4.6) — open tray",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0014",
     "indication": "Open-tray transfer onto Ø 4.6 mm SRA shoulder — splinted technique"},

    # ── LAB ANALOGS — LEVEL A (IMPLANT-LEVEL) ──────────────────────
    {"type": "implant_analog",
     "subtype": "Implant-level Analog — standard",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.2101",
     "indication": "Standard laboratory analog for implant-level model work"},
    {"type": "implant_analog",
     "subtype": "Implant-level Repositionable Analog (CARES)",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.2915",
     "indication": "Repositionable analog for digital workflow / CARES Mono"},

    # ── LAB ANALOGS — LEVEL B (ABUTMENT / SRA-LEVEL) ───────────────
    {"type": "implant_analog",
     "subtype": "Abutment-level Analog — Crown (Ø 3.5 SRA)",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.0013", "ref_to_verify": True,
     "indication": "Analog mirroring Ø 3.5 mm SRA shoulder — single crown model"},
    {"type": "implant_analog",
     "subtype": "Abutment-level Analog — Bridge / Bar (Ø 3.5 SRA)",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.0011",
     "indication": "Analog mirroring Ø 3.5 mm SRA shoulder — bridge/bar model"},
    {"type": "implant_analog",
     "subtype": "Abutment-level Analog — Crown (Ø 4.6 SRA)",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.0014", "ref_to_verify": True,
     "indication": "Analog mirroring Ø 4.6 mm SRA shoulder — single crown model"},
    {"type": "implant_analog",
     "subtype": "Abutment-level Analog — Bridge / Bar (Ø 4.6 SRA)",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": [], "torque_ncm": None,
     "catalog_code": "025.0012",
     "indication": "Analog mirroring Ø 4.6 mm SRA shoulder — bridge/bar model"},

    # ── SCAN BODIES — LEVEL A (IMPLANT-LEVEL) ──────────────────────
    {"type": "scan_body",
     "subtype": "Implant-level — CARES® Mono-Scanbody",
     "platform": "NC", "workflow_level": "implant",
     "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["PEEK"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.2915",
     "indication": "Digital scan body for implant-level CAD/CAM workflow"},

    # ── SCAN BODIES — LEVEL B (ABUTMENT / SRA-LEVEL) ───────────────
    {"type": "scan_body",
     "subtype": "Abutment-level (Ø 3.5 SRA) — CARES® Scanbody for SRA",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["PEEK"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0000",
     "indication": "Digital scan body for Ø 3.5 mm SRA shoulder"},
    {"type": "scan_body",
     "subtype": "Abutment-level (Ø 4.6 SRA) — CARES® Scanbody for SRA",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["PEEK"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0001",
     "indication": "Digital scan body for Ø 4.6 mm SRA shoulder"},

    # ── TEMPORARY ABUTMENTS (TAN / PMMA) ───────────────────────────
    {"type": "temporary_abutment", "subtype": "Temporary Abutment, TAN — Crown",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.2371",
     "indication": "Immediate / interim single-crown temporization"},
    {"type": "temporary_abutment", "subtype": "Temporary Abutment, TAN — Bridge",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "024.2372",
     "indication": "Immediate / interim bridge temporization"},

    # ── ANATOMIC ABUTMENTS (cementable, straight + angled) ─────────
    {"type": "final_abutment", "subtype": "Anatomic Abutment — straight (0°) — GH 2 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2102",
     "indication": "Cement-retained single crown — anatomic emergence"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — straight (0°) — GH 3.5 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2104",
     "indication": "Cement-retained single crown — anatomic emergence"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — angled 15° — GH 2 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2152",
     "indication": "Cement-retained single crown — corrects 15° axis divergence"},
    {"type": "final_abutment", "subtype": "Anatomic Abutment — angled 15° — GH 3.5 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [3.5], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2154",
     "indication": "Cement-retained single crown — corrects 15° axis divergence"},

    # ── CEMENTABLE ABUTMENTS (Ø 3.5 shoulder — GH 1/2/3/5.5) ───────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 1 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2311",
     "indication": "Cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 2 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2312",
     "indication": "Cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 3 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2313",
     "indication": "Cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — straight — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [5.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2315",
     "indication": "Cementable abutment for crown / bridge — deep ridge"},

    # ── CEMENTABLE ABUTMENTS (Ø 4.6 shoulder — GH 1/2/3/5.5) ───────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 1 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2321",
     "indication": "Wider cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 2 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2322",
     "indication": "Wider cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2323",
     "indication": "Wider cementable abutment for crown / bridge"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — straight — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [5.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2325",
     "indication": "Wider cementable abutment for crown / bridge — deep ridge"},

    # ── CEMENTABLE ABUTMENTS — angled 15° variants ─────────────────
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 3.5 — angled 15° — GH 3 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2317",
     "indication": "Cementable angulated abutment — 15° axis correction"},
    {"type": "final_abutment", "subtype": "Cementable Abutment Ø 4.6 — angled 15° — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["cement"], "torque_ncm": 35,
     "catalog_code": "022.2327",
     "indication": "Wider cementable angulated abutment — 15° axis correction"},

    # ── VARIOBASE FOR CROWN — Ø 3.8 (straight + angled 17°) ─────────
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 3.8 — straight — GH 1 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "025.2921",
     "indication": "Ti-base for cement- or screw-retained single crown"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 3.8 — straight — GH 2 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0102",
     "indication": "Ti-base for cement- or screw-retained single crown"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 3.8 — straight — GH 3 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0104",
     "indication": "Ti-base for cement- or screw-retained single crown"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 3.8 — angled 17° — GH 2 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [2.0], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0106",
     "indication": "Angulated Ti-base — 17° axis correction"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 3.8 — angled 17° — GH 3 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [3.0], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0108",
     "indication": "Angulated Ti-base — 17° axis correction"},

    # ── VARIOBASE FOR CROWN — Ø 4.1 (straight + angled 15°) ────────
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 4.1 — straight — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 4.1, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0084",
     "indication": "Wider Ti-base for cement- or screw-retained single crown"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 4.1 — straight — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 4.1, "gingival_heights_mm": [5.5], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0093",
     "indication": "Wider Ti-base for cement- or screw-retained single crown — deep ridge"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 4.1 — angled 15° — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 4.1, "gingival_heights_mm": [3.5], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0110",
     "indication": "Wider angulated Ti-base — 15° axis correction"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown, Ø 4.1 — angled 15° — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 4.1, "gingival_heights_mm": [5.5], "angulation_deg": 15,
     "material": ["Titanium"], "retention": ["screw", "cement"], "torque_ncm": 35,
     "catalog_code": "022.0111",
     "indication": "Wider angulated Ti-base — 15° axis correction, deep ridge"},

    # ── VARIOBASE FOR CROWN AS (Angled Screw 25°) ──────────────────
    {"type": "variobase_crown", "subtype": "Variobase for Crown AS — angled-screw 25° — GH 1.5 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "angulation_deg": 25,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01245",
     "indication": "Angled-screw Ti-base — palatal screw access, 25°"},
    {"type": "variobase_crown", "subtype": "Variobase for Crown AS — angled-screw 25° — GH 2.5 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [2.5], "angulation_deg": 25,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01255",
     "indication": "Angled-screw Ti-base — palatal screw access, 25°"},

    # ── VARIOBASE FOR BRIDGE / BAR (cylindrical) ───────────────────
    {"type": "variobase_bridge", "subtype": "Variobase for Bridge / Bar, cylindrical — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [3.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01265",
     "indication": "Cylindrical Ti-base for multi-unit bridge or bar"},
    {"type": "variobase_bridge", "subtype": "Variobase for Bridge / Bar, cylindrical — GH 4.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [4.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01305",
     "indication": "Cylindrical Ti-base for multi-unit bridge or bar"},
    {"type": "variobase_bridge", "subtype": "Variobase for Bridge / Bar, cylindrical — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [5.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01345",
     "indication": "Cylindrical Ti-base for multi-unit bridge or bar — deep ridge"},

    # ── VARIOBASE CYLINDRICAL FOR SRA (level-B Ti-base) ────────────
    {"type": "variobase_bridge", "subtype": "Variobase Cylindrical for SRA — Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "023.0027",
     "indication": "Ti-base mounting onto Ø 3.5 mm SRA shoulder"},
    {"type": "variobase_bridge", "subtype": "Variobase Cylindrical for SRA — Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "023.0028",
     "indication": "Ti-base mounting onto Ø 4.6 mm SRA shoulder"},

    # ── SCREW-RETAINED ABUTMENTS (SRA / Multi-Base) ────────────────
    # Straight (0°) Ø 3.5
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — straight (0°) — GH 1 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01365",
     "indication": "Multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — straight (0°) — GH 2 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01385",
     "indication": "Multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — straight (0°) — GH 3 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01405",
     "indication": "Multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — straight (0°) — GH 4 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [4.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01425",
     "indication": "Multi-unit screw-retained abutment, straight"},
    # Angled 17° Ø 3.5 — Type A (anti-rotation) + Type B (rotational, for multi-unit)
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — angled 17° Type A — GH 1.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [1.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01375",
     "indication": "Angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 3.5 — angled 17° Type B — GH 1.5 mm",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [1.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01395",
     "indication": "Angled SRA 17° — Type B (rotational), multi-unit"},
    # Straight (0°) Ø 4.6
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — straight (0°) — GH 1 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01445",
     "indication": "Wider multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — straight (0°) — GH 2 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01465",
     "indication": "Wider multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — straight (0°) — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01485",
     "indication": "Wider multi-unit screw-retained abutment, straight"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — straight (0°) — GH 4 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [4.0], "angulation_deg": 0,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01505",
     "indication": "Wider multi-unit screw-retained abutment, straight"},
    # Angled 17° Ø 4.6 — Type A + Type B
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — angled 17° Type A — GH 2.5 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01455",
     "indication": "Wider angled SRA 17° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — angled 17° Type B — GH 2.5 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 17,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01475",
     "indication": "Wider angled SRA 17° — Type B (rotational), multi-unit"},
    # Angled 30° Ø 4.6 — Type A + Type B
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — angled 30° Type A — GH 2.5 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 30,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01525",
     "indication": "Wider angled SRA 30° — Type A (anti-rotation), single unit"},
    {"type": "screw_retained_abutment", "subtype": "SRA Ø 4.6 — angled 30° Type B — GH 2.5 mm",
     "platform": "NC", "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 30,
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "022.01535",
     "indication": "Wider angled SRA 30° — Type B (rotational), multi-unit"},

    # ── BURN-OUT COPINGS ───────────────────────────────────────────
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown — GH 3.5 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [3.5],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2756",
     "indication": "Burn-out for casting / pressing on Variobase crown"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown — GH 5.5 mm",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [5.5],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0018",
     "indication": "Burn-out for casting / pressing on Variobase crown"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Crown AS 25°",
     "platform": "NC", "diameter_mm": 3.8, "gingival_heights_mm": [], "angulation_deg": 25,
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0029",
     "indication": "Burn-out for angled-screw Variobase AS"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Cylindrical SRA Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0031",
     "indication": "Burn-out for cylindrical SRA-level Ti-base — Ø 3.5"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for Variobase Cylindrical SRA Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.0032",
     "indication": "Burn-out for cylindrical SRA-level Ti-base — Ø 4.6"},

    # ── GOLD COPINGS ───────────────────────────────────────────────
    {"type": "gold_coping", "subtype": "Gold Coping — Crown, Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Gold"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2751",
     "indication": "Gold coping for crown casting on Ø 3.5 mm SRA"},
    {"type": "gold_coping", "subtype": "Gold Coping — Bridge, Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Gold"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4754",
     "indication": "Gold coping for bridge casting on Ø 4.6 mm SRA"},

    # ── TITANIUM COPINGS — FINAL ───────────────────────────────────
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Crown, Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2747",
     "indication": "Final titanium coping — single crown, Ø 3.5 mm SRA"},
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Bridge, Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2749",
     "indication": "Final titanium coping — bridge, Ø 3.5 mm SRA"},
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Crown, Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4747",
     "indication": "Final titanium coping — single crown, Ø 4.6 mm SRA"},
    {"type": "titanium_coping", "subtype": "Final Titanium Coping — Bridge, Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.4751",
     "indication": "Final titanium coping — bridge, Ø 4.6 mm SRA"},

    # ── TITANIUM COPINGS — TEMPORARY ───────────────────────────────
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Crown, Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0021",
     "indication": "Temporary titanium coping — single crown, Ø 3.5 mm SRA"},
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Bridge, Ø 3.5",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0022",
     "indication": "Temporary titanium coping — bridge, Ø 3.5 mm SRA"},
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Crown, Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0023",
     "indication": "Temporary titanium coping — single crown, Ø 4.6 mm SRA"},
    {"type": "titanium_coping", "subtype": "Temporary Titanium Coping — Bridge, Ø 4.6",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [],
     "material": ["Titanium"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0024",
     "indication": "Temporary titanium coping — bridge, Ø 4.6 mm SRA"},

    # ── PLASTIC COPINGS for cementable abutments ───────────────────
    {"type": "plastic_coping", "subtype": "Plastic Coping for Cementable Abutments — Crown, Ø 3.5",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2316",
     "indication": "Plastic coping — pattern for cast crown on cementable abutment"},
    {"type": "plastic_coping", "subtype": "Plastic Coping for Cementable Abutments — Bridge, Ø 3.5",
     "platform": "NC", "diameter_mm": 3.5, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2310",
     "indication": "Plastic coping — pattern for cast bridge on cementable abutment"},
    {"type": "plastic_coping", "subtype": "Plastic Coping for Cementable Abutments — Crown, Ø 5.0",
     "platform": "NC", "diameter_mm": 5.0, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2326",
     "indication": "Plastic coping — pattern for wider cast crown"},
    {"type": "plastic_coping", "subtype": "Plastic Coping for Cementable Abutments — Bridge, Ø 5.0",
     "platform": "NC", "diameter_mm": 5.0, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "023.2320",
     "indication": "Plastic coping — pattern for wider cast bridge"},

    # ── PROSTHETIC / LAB SCREWS ────────────────────────────────────
    {"type": "prosthetic_screw", "subtype": "Basal Screw — NC (for Cementable Abutments)",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "025.2900",
     "indication": "Basal screw for cementable abutments"},
    {"type": "prosthetic_screw", "subtype": "Basal Screw — NC (for pre-milled / Variobase)",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 35,
     "catalog_code": "025.2926",
     "indication": "Basal screw for Variobase / pre-milled abutments"},
    {"type": "prosthetic_screw", "subtype": "Occlusal Screw — NC",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["TAN"], "retention": ["screw"], "torque_ncm": 15,
     "catalog_code": "023.4763",
     "indication": "Occlusal screw for screw-retained restorations"},
    {"type": "prosthetic_screw", "subtype": "Lab Processing Screw — NC (L 20 mm)",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0006",
     "indication": "Long lab-processing screw for try-in / framework verification"},
    {"type": "prosthetic_screw", "subtype": "Lab Processing Screw — NC (L 10 mm)",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Stainless steel"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "025.0052",
     "indication": "Short lab-processing screw for try-in / framework verification"},

    # ── PROTECTIVE CAPS for SRA (chair-side handling) ──────────────
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — Ø 3.5 / GH 3.5 mm",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [3.5],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.0019-04",
     "indication": "Protects Ø 3.5 mm SRA between sessions"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — Ø 3.5 / GH 5 mm",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 3.5, "gingival_heights_mm": [5.0],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.2323-04",
     "indication": "Protects Ø 3.5 mm SRA between sessions"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — Ø 4.6 / GH 5.1 mm",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [5.1],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.4323-04",
     "indication": "Protects Ø 4.6 mm SRA between sessions"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — Ø 4.6 / GH 6.5 mm",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [6.5],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.2324-04",
     "indication": "Protects Ø 4.6 mm SRA between sessions — deep ridge"},
    {"type": "protective_cap", "subtype": "Protective Cap for SRA — Ø 4.6 / GH 6.6 mm",
     "platform": "NC", "workflow_level": "abutment",
     "diameter_mm": 4.6, "gingival_heights_mm": [6.6],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "024.4324-04",
     "indication": "Protects Ø 4.6 mm SRA between sessions — deep ridge"},

    # ── PRE-MILLED ABUTMENT BLANKS (Medentika holder) ──────────────
    {"type": "premilled_blank", "subtype": "Pre-milled Abutment Blank — H 11.5 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [11.5],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "022.0028",
     "indication": "Custom-milled abutment blank (Medentika holder)"},
    {"type": "premilled_blank", "subtype": "Pre-milled Abutment Blank — H 15.8 mm",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [15.8],
     "material": ["Titanium"], "retention": ["screw"], "torque_ncm": None,
     "catalog_code": "022.0029",
     "indication": "Custom-milled abutment blank (Medentika holder) — tall"},

    # ── WAX-UP SLEEVE ──────────────────────────────────────────────
    {"type": "wax_up_sleeve", "subtype": "Wax-up Sleeve",
     "platform": "NC", "diameter_mm": None, "gingival_heights_mm": [],
     "material": ["Polymer"], "retention": ["friction"], "torque_ncm": None,
     "catalog_code": "025.2903",
     "indication": "Lab wax-up sleeve for framework planning"},

    # ── NOVALOC® ABUTMENTS (iter-305) — overdenture retention ──────
    # Novaloc carbon-coated titanium abutments for retentive
    # (snap-on) removable overdentures.  Available only for NC and
    # RC platforms.  15° angulated variants combine with a Novaloc
    # retentive cap (housed in the denture) to provide up to 20° of
    # total path-of-insertion correction.
    # NC 0° — GH 1 / 2 / 3 / 4 / 5 / 6 mm  (REF 022.0046 – 022.0051)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 1 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [1.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0046", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 2 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0047", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0048", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 4 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0049", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 5 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0050", "indication": "Snap-on overdenture retention — straight"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — straight (0°) — GH 6 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 0,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0051", "indication": "Snap-on overdenture retention — straight, deep ridge"},
    # NC 15° Type A — GH 2 / 3 / 4 / 5 / 6 mm  (REF 022.0062 – 022.0066)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 2 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0062",
     "indication": "Angled Novaloc 15° Type A — anti-rotation, single overdenture attachment (up to 20° path-of-insertion correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0063",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 4 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0064",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 5 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0065",
     "indication": "Angled Novaloc 15° Type A — anti-rotation (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type A — GH 6 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0066", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type A — anti-rotation, deep ridge (up to 20° path correction)"},
    # NC 15° Type B — GH 2 / 3 / 4 / 5 / 6 mm  (REF 022.0072 – 022.0076)
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 2 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [2.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0072",
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture (up to 20° path correction)"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 3 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [3.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0073", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 4 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [4.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0074",
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 5 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [5.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0075", "ref_to_verify": True,
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture"},
    {"type": "novaloc_abutment", "subtype": "Novaloc® Abutment — angled 15° Type B — GH 6 mm",
     "platform": "NC", "diameter_mm": 4.0, "gingival_heights_mm": [6.0], "angulation_deg": 15,
     "material": ["Titanium", "ADLC-coated"], "retention": ["snap"], "torque_ncm": 35,
     "catalog_code": "022.0076",
     "indication": "Angled Novaloc 15° Type B — rotational, splinted overdenture, deep ridge"},
]


# Shared with iter-301 — the same 3 BLT systems carry the NC catalog.
SYSTEMS_USING_NC: List[str] = [
    "BLT Roxolid SLActive",
    "BLT Roxolid SLA",
    "BLT Ti SLA",
]


def expanded_nc_components_for(system_name: str) -> List[Dict]:
    """Return a deep copy of the NC (Ø 3.3 mm) component list for the
    given BLT system. Returns [] for systems outside this batch."""
    if system_name not in SYSTEMS_USING_NC:
        return []
    return copy.deepcopy(NC_COMPONENTS)
