"""
Straumann BLX rich prosthetic component catalog (iter-293, Feb 2026)

Expands the thin 10-row per-platform stub from
`straumann_blx_data.COMPONENT_FAMILIES_BY_PLATFORM` into the full per-SKU
brochure detail (~115 entries) so the BLX systems in the Implant Database
show the same depth as Alpha-Bio / Neodent / MIS LANCE+.

Source: Straumann BLX Prosthetic Components Catalogue
(job artifact `BLX Catalogue.pdf`, iter-293).

Shape matches the existing `implant_catalog.components` schema used by other
brands: `type`, `subtype`, `platform`, `diameter_mm`, `gingival_heights_mm`,
`angulation_deg`, `material`, `retention`, `torque_ncm`, `catalog_code`,
`abutment_height_mm`, `indication`.

Platform mapping
────────────────
The Straumann BLX prosthetic line uses TWO transmucosal platforms:
  • RB = Regular Base — for Ø3.5 / 4.0 / 4.5 mm implants
  • WB = Wide Base — for Ø5.0 / 5.5 / 6.0 mm implants

Most prosthetic SKUs are shared (RB/WB compatible). WB-specific SKUs are
documented in catalog pages 25-29 and are filed under the WB platform list
only. RB/WB shared SKUs appear in both platform lists.

Torque targets (per Straumann BLX Basic Information):
  • Final abutments: 35 Ncm
  • Cover screws / Healing abutments / Lab screws: 15 Ncm (hand-tighten)
  • Novaloc / Locator-style abutments: 35 Ncm
"""

from typing import Dict, List


# ── Shared SRA copings & bar components (used by both RB and WB) ──────────
_SRA_SHARED: List[Dict] = [
    # Impression posts at abutment level (single crown — engaging)
    {"type": "impression_post", "subtype": "SRA Single-Crown Open-tray (engaging)",
     "platform": "SRA", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "catalog_code": "025.2244",
     "indication": "Open-tray impression, single crown on Screw-retained Abutment"},
    {"type": "impression_post", "subtype": "SRA Single-Crown Closed-tray (engaging)",
     "platform": "SRA", "material": ["TAN", "POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "catalog_code": "025.2246",
     "indication": "Closed-tray impression, single crown on Screw-retained Abutment"},
    # Impression posts at abutment level (multi-unit — non-engaging)
    {"type": "impression_post", "subtype": "SRA Multi-Unit Open-tray (non-engaging)",
     "platform": "SRA", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "catalog_code": "025.0012",
     "indication": "Open-tray impression, multi-unit on Screw-retained Abutment"},
    {"type": "impression_post", "subtype": "SRA Multi-Unit Closed-tray (non-engaging)",
     "platform": "SRA", "material": ["TAN", "POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "catalog_code": "025.0014",
     "indication": "Closed-tray impression, multi-unit on Screw-retained Abutment"},
    # Digital impression
    {"type": "scan_body", "subtype": "CARES® Mono Scanbody for SRA",
     "platform": "SRA", "material": ["PEEK"], "retention": ["screw"],
     "diameter_mm": 4.6, "catalog_code": "025.0001",
     "indication": "Digital workflow on Screw-retained Abutments (incl. fixation screw)"},
    # Analogs for SRA
    {"type": "implant_analog", "subtype": "SRA Repositionable Analog (digital)",
     "platform": "SRA", "material": ["stainless_steel"], "retention": [],
     "diameter_mm": 4.6, "catalog_code": "025.0008",
     "indication": "Fully digital workflow on SRA"},
    {"type": "implant_analog", "subtype": "SRA Analog, straight",
     "platform": "SRA", "material": ["TAN"], "retention": [],
     "diameter_mm": 4.6, "catalog_code": "023.4756",
     "indication": "Stone model, straight SRA"},
    {"type": "implant_analog", "subtype": "SRA Analog, straight, edentulous",
     "platform": "SRA", "material": ["TAN"], "retention": [],
     "diameter_mm": 4.6, "catalog_code": "025.0050",
     "indication": "Edentulous stone model, straight SRA"},
    {"type": "implant_analog", "subtype": "SRA Analog, angled (17°/30°)",
     "platform": "SRA", "material": ["TAN"], "retention": [],
     "diameter_mm": 4.6, "angulation_deg": 17, "catalog_code": "023.4757",
     "indication": "Stone model, angled SRA"},
    # Lab auxiliaries
    {"type": "lab_auxiliary", "subtype": "SRA Polishing Aid",
     "platform": "SRA", "material": ["TAN"], "catalog_code": "025.0005",
     "indication": "Lab polishing on SRA"},
    {"type": "lab_auxiliary", "subtype": "SRA Lab Processing Screw, 20 mm",
     "platform": "SRA", "material": ["stainless_steel"], "abutment_height_mm": 20,
     "catalog_code": "025.0006", "indication": "Lab work on Screw-retained Abutments"},
    {"type": "lab_auxiliary", "subtype": "SRA Lab Processing Screw, 10 mm",
     "platform": "SRA", "material": ["stainless_steel"], "abutment_height_mm": 10,
     "catalog_code": "025.0052", "indication": "Lab work on Screw-retained Abutments"},
    # Protective caps
    {"type": "protective_cap", "subtype": "SRA Protective Cap, 5.1 mm",
     "platform": "SRA", "material": ["PEEK"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 5.1, "catalog_code": "024.4323-04",
     "indication": "Healing on SRA, incl. screw 023.4763 (4-pack)"},
    {"type": "protective_cap", "subtype": "SRA Protective Cap, 6.6 mm",
     "platform": "SRA", "material": ["PEEK"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 6.6, "catalog_code": "024.4324-04",
     "indication": "Healing on SRA, incl. screw 023.4763 (4-pack)"},
    {"type": "protective_cap", "subtype": "SRA Protective Cap, 8.1 mm",
     "platform": "SRA", "material": ["PEEK"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 8.1, "catalog_code": "024.4325-04",
     "indication": "Healing on SRA, incl. screw 023.4763 (4-pack)"},
    # Titanium copings for SRA
    {"type": "sra_coping", "subtype": "Titanium Coping for SRA, crown",
     "platform": "SRA", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 11, "torque_ncm": 15,
     "catalog_code": "023.4750",
     "indication": "Single crown on SRA Ø4.6 mm (incl. screw 023.4763)"},
    {"type": "sra_coping", "subtype": "Titanium Coping for SRA, bridge",
     "platform": "SRA", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 11, "torque_ncm": 15,
     "catalog_code": "023.4751",
     "indication": "Bridge on SRA Ø4.6 mm (incl. screw 023.4763)"},
    {"type": "sra_coping", "subtype": "Titanium Coping for SRA, bar",
     "platform": "SRA", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 5.5, "torque_ncm": 15,
     "catalog_code": "023.4752",
     "indication": "Bar reconstruction on SRA Ø4.6 mm"},
    # Gold copings for SRA
    {"type": "sra_coping", "subtype": "Gold Coping for SRA, crown",
     "platform": "SRA", "material": ["Ceramicor", "POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "torque_ncm": 15, "catalog_code": "023.4753",
     "indication": "Single crown on SRA, alloy weight 0.44 g (incl. screw 023.4763)"},
    {"type": "sra_coping", "subtype": "Gold Coping for SRA, bridge",
     "platform": "SRA", "material": ["Ceramicor", "POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "torque_ncm": 15, "catalog_code": "023.4754",
     "indication": "Bridge on SRA, alloy weight 0.469 g (incl. screw 023.4763)"},
    {"type": "sra_coping", "subtype": "Gold Coping for SRA, bar",
     "platform": "SRA", "material": ["Ceramicor"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 5.5, "torque_ncm": 15,
     "catalog_code": "023.4755",
     "indication": "Bar on SRA, alloy weight 0.744 g (incl. screw 023.4763)"},
    # Burn-out copings for SRA
    {"type": "burnout_coping", "subtype": "Burn-out Coping for SRA, crown",
     "platform": "SRA", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 11, "catalog_code": "023.4748",
     "indication": "Cast-on crown framework on SRA"},
    {"type": "burnout_coping", "subtype": "Burn-out Coping for SRA, bridge/bar",
     "platform": "SRA", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.6, "abutment_height_mm": 11, "catalog_code": "023.4758",
     "indication": "Cast-on bridge/bar framework on SRA"},
    # Dolder Bar profiles & matrices
    {"type": "bar_profile", "subtype": "Dolder® Bar Gold, mini (egg-shaped)",
     "platform": "SRA", "material": ["Elitor"], "abutment_height_mm": 25,
     "catalog_code": "048.411",
     "indication": "Gold bar overdenture, height 2.3 mm × width 1.6 mm"},
    {"type": "bar_profile", "subtype": "Dolder® Bar Gold, regular (egg-shaped)",
     "platform": "SRA", "material": ["Elitor"], "abutment_height_mm": 25,
     "catalog_code": "048.412",
     "indication": "Gold bar overdenture, height 3 mm × width 2.2 mm"},
    {"type": "bar_profile", "subtype": "Dolder® Bar Titanium, mini",
     "platform": "SRA", "material": ["titanium"], "abutment_height_mm": 50,
     "catalog_code": "048.466",
     "indication": "Titanium bar overdenture, height 2.3 mm × width 1.6 mm"},
    {"type": "bar_profile", "subtype": "Dolder® Bar Titanium, regular",
     "platform": "SRA", "material": ["titanium"], "abutment_height_mm": 50,
     "catalog_code": "048.465",
     "indication": "Titanium bar overdenture, height 3 mm × width 2.2 mm"},
    {"type": "bar_profile", "subtype": "Dolder® Bar Plastic (try-in), mini",
     "platform": "SRA", "material": ["PMMA"], "abutment_height_mm": 80,
     "catalog_code": "048.461",
     "indication": "Plastic bar pattern, height 2.3 mm × width 1.6 mm"},
    {"type": "bar_profile", "subtype": "Dolder® Bar Plastic (try-in), regular",
     "platform": "SRA", "material": ["PMMA"], "abutment_height_mm": 80,
     "catalog_code": "048.460",
     "indication": "Plastic bar pattern, height 3 mm × width 2.2 mm"},
    {"type": "bar_matrix", "subtype": "Dolder® Bar Matrix Gold, mini",
     "platform": "SRA", "material": ["Elitor", "brass"], "catalog_code": "048.413",
     "indication": "Gold bar female, height 2.75 mm × width 3.6 mm (incl. spacer)"},
    {"type": "bar_matrix", "subtype": "Dolder® Bar Matrix Gold, regular",
     "platform": "SRA", "material": ["Elitor", "brass"], "catalog_code": "048.414",
     "indication": "Gold bar female, height 3.5 mm × width 4.6 mm (incl. spacer)"},
    {"type": "bar_matrix", "subtype": "Dolder® Bar Matrix Titanium, mini",
     "platform": "SRA", "material": ["titanium", "brass"], "catalog_code": "048.471",
     "indication": "Titanium bar female, height 2.9 mm × width 2.8 mm (incl. spacer)"},
    {"type": "bar_matrix", "subtype": "Dolder® Bar Matrix Titanium, standard",
     "platform": "SRA", "material": ["titanium", "brass"], "catalog_code": "048.470",
     "indication": "Titanium bar female, height 3.7 mm × width 3.6 mm (incl. spacer)"},
    {"type": "bar_tool", "subtype": "Activator Set (3-part)",
     "platform": "SRA", "material": ["stainless_steel"], "catalog_code": "046.150",
     "indication": "Activator for all Dolder bar matrices"},
    {"type": "bar_tool", "subtype": "Deactivator, mini",
     "platform": "SRA", "material": ["Grilon", "brass"], "catalog_code": "046.151",
     "indication": "Deactivator for Dolder Bar Matrix mini"},
    {"type": "bar_tool", "subtype": "Deactivator, standard",
     "platform": "SRA", "material": ["Grilon", "brass"], "catalog_code": "046.152",
     "indication": "Deactivator for Dolder Bar Matrix standard"},
    # Auxiliary / planning
    {"type": "auxiliary", "subtype": "Pro Arch Planning Guide",
     "platform": "SRA", "material": ["TAV", "titanium"], "catalog_code": "026.0016",
     "indication": "Visual guide for tilted implant placement (Pro Arch)"},
]


# ── Novaloc® attachments (shared accessory line, primarily RB) ─────────────
_NOVALOC_SHARED: List[Dict] = [
    # Novaloc 0° straight (RB Ø3.8)
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 1.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4501",
     "indication": "Overdenture, straight (covers GH 1.5)"},
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 2.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [2.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4502",
     "indication": "Overdenture, straight"},
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 3.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4503",
     "indication": "Overdenture, straight"},
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 4.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [4.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4504",
     "indication": "Overdenture, straight"},
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 5.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [5.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4505",
     "indication": "Overdenture, straight"},
    {"type": "locator_abutment", "subtype": "Novaloc® 0°, GH 6.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [6.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.4506",
     "indication": "Overdenture, straight"},
    # Novaloc 15° angled
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 2.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [2.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4507",
     "indication": "Overdenture, divergent implants up to 30°"},
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 3.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [3.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4508",
     "indication": "Overdenture, divergent implants up to 30°"},
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 4.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [4.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4509",
     "indication": "Overdenture, divergent implants up to 30°"},
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 5.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [5.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4510",
     "indication": "Overdenture, divergent implants up to 30°"},
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 6.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [6.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4511",
     "indication": "Overdenture, divergent implants up to 30°"},
    {"type": "locator_abutment", "subtype": "Novaloc® 15°, GH 7.5 mm",
     "platform": "RB", "material": ["TAV"], "retention": ["snap"],
     "diameter_mm": 3.8, "gingival_heights_mm": [7.5], "angulation_deg": 15,
     "torque_ncm": 35, "catalog_code": "062.4512",
     "indication": "Overdenture, divergent implants up to 30°"},
    # Novaloc processing & inserts
    {"type": "locator_processing", "subtype": "Novaloc® Processing Package, Titanium (2-pack)",
     "platform": "RB", "material": ["titanium", "POM", "PEEK", "silicone"],
     "catalog_code": "2010.601-STM",
     "indication": "Ti matrix housing kit with light/medium/strong inserts"},
    {"type": "locator_processing", "subtype": "Novaloc® Processing Package, PEEK (2-pack)",
     "platform": "RB", "material": ["PEEK", "POM", "silicone"],
     "catalog_code": "2010.611-STM",
     "indication": "PEEK matrix housing kit with light/medium/strong inserts"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert red — extra-light (~300 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.710-STM",
     "indication": "Lowest retention (4-pack)"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert white — light (~750 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.711-STM",
     "indication": "Light retention (4-pack)"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert yellow — medium (~1200 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.712-STM",
     "indication": "Medium retention (4-pack)"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert green — strong (~1650 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.713-STM",
     "indication": "Strong retention (4-pack)"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert blue — extra-strong (~2100 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.714-STM",
     "indication": "Extra-strong retention (4-pack)"},
    {"type": "retention_insert", "subtype": "Novaloc® Insert black — ultra-strong (~2550 g)",
     "platform": "RB", "material": ["PEEK"], "catalog_code": "2010.715-STM",
     "indication": "Ultra-strong retention (4-pack)"},
    {"type": "matrix_housing", "subtype": "Novaloc® Matrix Housing, Titanium",
     "platform": "RB", "material": ["titanium", "POM"],
     "catalog_code": "2010.701-STM", "indication": "Standard Ti housing (4-pack)"},
    {"type": "matrix_housing", "subtype": "Novaloc® Matrix Housing, PEEK",
     "platform": "RB", "material": ["PEEK", "POM"],
     "catalog_code": "2010.702-STM", "indication": "Lightweight PEEK housing (4-pack)"},
    {"type": "matrix_housing", "subtype": "Novaloc® Matrix Housing with Attachment Option",
     "platform": "RB", "material": ["titanium", "POM"],
     "catalog_code": "2010.703-STM", "indication": "Ti housing with attachment slot"},
]


# ── RB Platform components ─────────────────────────────────────────────────
_RB_COMPONENTS: List[Dict] = [
    # Cover screw (implicit — Straumann BLX uses Closure Screws sold with implant)
    {"type": "cover_screw", "subtype": "RB Closure Screw",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "torque_ncm": 15, "catalog_code": "—",
     "indication": "Submerged two-stage healing (included with implant kit)"},

    # ── Healing abutments — Crown emergence Ø4 mm (for Ø3.8 abutments) ────
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 1.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42025",
     "indication": "Transmucosal healing, narrow emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 1.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42035",
     "indication": "Transmucosal healing, narrow emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 2.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [2.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42045",
     "indication": "Transmucosal healing, narrow emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 2.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [2.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42055",
     "indication": "Transmucosal healing, narrow emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 3.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [3.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42065",
     "indication": "Transmucosal healing, narrow emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø4, GH 3.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 4.0, "gingival_heights_mm": [3.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42075",
     "indication": "Transmucosal healing, narrow emergence"},

    # ── Healing abutments — Crown emergence Ø5 mm (for Ø4.5 abutments) ────
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 1.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42125",
     "indication": "Transmucosal healing, standard emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 1.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42135",
     "indication": "Transmucosal healing, standard emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 2.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [2.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42145",
     "indication": "Transmucosal healing, standard emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 2.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [2.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42155",
     "indication": "Transmucosal healing, standard emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 3.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [3.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42165",
     "indication": "Transmucosal healing, standard emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø5, GH 3.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [3.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42175",
     "indication": "Transmucosal healing, standard emergence"},

    # ── Healing abutments — Crown emergence Ø6.5 mm (for Ø6 abutments) ────
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 1.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42225",
     "indication": "Transmucosal healing, wide emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 1.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42235",
     "indication": "Transmucosal healing, wide emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 2.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [2.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42245",
     "indication": "Transmucosal healing, wide emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 2.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [2.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42255",
     "indication": "Transmucosal healing, wide emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 3.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [3.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42265",
     "indication": "Transmucosal healing, wide emergence"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Crown Ø6.5, GH 3.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.5, "gingival_heights_mm": [3.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42275",
     "indication": "Transmucosal healing, wide emergence"},

    # ── Bridge healing abutments ──────────────────────────────────────────
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Bridge/Bar Ø5, GH 1.5, H 2",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.42325",
     "indication": "Transmucosal healing — bridge / bar"},
    {"type": "healing_abutment", "subtype": "RB Healing Abutment Bridge/Bar Ø5, GH 1.5, H 4",
     "platform": "RB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 5.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.42335",
     "indication": "Transmucosal healing — bridge / bar"},

    # ── Temporary abutments — Crown ───────────────────────────────────────
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø3.8, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "torque_ncm": 15,
     "catalog_code": "064.4362", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø3.8, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [2.5], "torque_ncm": 15,
     "catalog_code": "064.4363", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø3.8, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [3.5], "torque_ncm": 15,
     "catalog_code": "064.4364", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø4.5, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "torque_ncm": 15,
     "catalog_code": "064.4372", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø4.5, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [2.5], "torque_ncm": 15,
     "catalog_code": "064.4373", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø4.5, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [3.5], "torque_ncm": 15,
     "catalog_code": "064.4374", "indication": "Provisional crown"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø6, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [2.5], "torque_ncm": 15,
     "catalog_code": "064.4382", "indication": "Provisional crown — wide emergence"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Crown Ø6, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [3.5], "torque_ncm": 15,
     "catalog_code": "064.4383", "indication": "Provisional crown — wide emergence"},
    {"type": "temporary_abutment", "subtype": "RB Temporary Abutment Bridge/Bar Ø4.5, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "torque_ncm": 15, "catalog_code": "064.4352",
     "indication": "Provisional bridge / bar"},

    # ── Anatomic Titanium abutments ───────────────────────────────────────
    {"type": "final_abutment", "subtype": "RB Anatomic Abutment, straight, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["cement"],
     "gingival_heights_mm": [2.5], "angulation_deg": 0, "torque_ncm": 35,
     "catalog_code": "062.4103",
     "indication": "Cement-retained single crown, parallel implants"},
    {"type": "final_abutment", "subtype": "RB Anatomic Abutment, straight, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["cement"],
     "gingival_heights_mm": [3.5], "angulation_deg": 0, "torque_ncm": 35,
     "catalog_code": "062.4104",
     "indication": "Cement-retained single crown, parallel implants"},
    {"type": "final_abutment", "subtype": "RB Anatomic Abutment, angled 17°, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["cement"],
     "gingival_heights_mm": [2.5], "angulation_deg": 17, "torque_ncm": 35,
     "catalog_code": "062.4153",
     "indication": "Cement-retained crown, off-axis implant"},
    {"type": "final_abutment", "subtype": "RB Anatomic Abutment, angled 17°, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["cement"],
     "gingival_heights_mm": [3.5], "angulation_deg": 17, "torque_ncm": 35,
     "catalog_code": "062.4154",
     "indication": "Cement-retained crown, off-axis implant"},

    # ── Gold abutments ────────────────────────────────────────────────────
    {"type": "final_abutment", "subtype": "RB Gold Abutment Crown Ø3.8, GH 1.5",
     "platform": "RB", "material": ["Ceramicor", "POM"], "retention": ["cement"],
     "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4410",
     "indication": "Cast-on crown, incl. screw 065.0036"},
    {"type": "final_abutment", "subtype": "RB Gold Abutment Crown Ø4.5, GH 1.5",
     "platform": "RB", "material": ["Ceramicor", "POM"], "retention": ["cement"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4420",
     "indication": "Cast-on crown, incl. screw 065.0036"},
    {"type": "final_abutment", "subtype": "RB Gold Abutment Bridge/Bar Ø4.5, GH 1.5",
     "platform": "RB", "material": ["Ceramicor", "POM"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4430",
     "indication": "Cast-on bridge/bar, incl. screw 065.0036"},

    # ── Variobase® for Crown ──────────────────────────────────────────────
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø3.8, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4934",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø3.8, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [2.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4935",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø3.8, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [3.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4936",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø4.5, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4944",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø4.5, GH 2.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [2.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4945",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown Ø4.5, GH 3.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [3.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4946",
     "indication": "CAD/CAM ceramic crown on ti-base"},
    {"type": "ti_base", "subtype": "RB Variobase® C Ø3.8, GH 1.5 (Sirona)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4981",
     "indication": "Variobase® C for Dentsply® Sirona® CEREC workflow"},
    {"type": "ti_base", "subtype": "RB Variobase® C Ø4.5, GH 1.5 (Sirona)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4982",
     "indication": "Variobase® C for Dentsply® Sirona® CEREC workflow"},
    {"type": "ti_base", "subtype": "RB Variobase® for Bridge/Bar Cylindrical Ø4.5, GH 1.5",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 3.5,
     "torque_ncm": 35, "catalog_code": "062.4961",
     "indication": "CAD/CAM bridge/bar on ti-base (incl. Cementation Aid 3)"},
    {"type": "ti_base", "subtype": "RB Variobase® Crown AS Ø4.5, GH 1.5 (Angulated Screw)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "angulation_deg": 25, "torque_ncm": 35, "catalog_code": "062.4972",
     "indication": "ASC up to 25° — aesthetic anterior crown"},

    # ── Burn-out Copings for Variobase® ───────────────────────────────────
    {"type": "burnout_coping", "subtype": "RB Burn-out Coping for Variobase® Crown Ø3.8",
     "platform": "RB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 3.8, "abutment_height_mm": 5.5, "catalog_code": "065.0014",
     "indication": "Cast-on crown framework, Variobase®"},
    {"type": "burnout_coping", "subtype": "RB Burn-out Coping for Variobase® Crown Ø4.5",
     "platform": "RB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.5, "abutment_height_mm": 5.5, "catalog_code": "065.0015",
     "indication": "Cast-on crown framework, Variobase®"},
    {"type": "burnout_coping", "subtype": "RB Burn-out Coping Bridge/Bar Ø4.5",
     "platform": "RB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.5, "abutment_height_mm": 3.5, "catalog_code": "065.0017",
     "indication": "Cast-on bridge/bar framework, Variobase®"},
    {"type": "burnout_coping", "subtype": "RB Burn-out Coping Bridge/Bar Ø4.5 (4-pack)",
     "platform": "RB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.5, "abutment_height_mm": 3.5, "catalog_code": "065.0017V4",
     "indication": "Cast-on bridge/bar framework, Variobase® (4-pack)"},
    {"type": "burnout_coping", "subtype": "RB Burn-out Coping AS Crown Ø4.5",
     "platform": "RB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 4.5, "abutment_height_mm": 5.5, "angulation_deg": 25,
     "catalog_code": "065.0018",
     "indication": "Angulated Screw Channel cast-on framework"},

    # ── Screw-retained abutments — 0° / 17° / 30° ────────────────────────
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 0° straight, GH 1.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [1.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.47225",
     "indication": "Pro Arch multi-unit, parallel implant"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 0° straight, GH 2.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [2.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.47235",
     "indication": "Pro Arch multi-unit, parallel implant"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 0° straight, GH 3.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.47245",
     "indication": "Pro Arch multi-unit, parallel implant"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 0° straight, GH 4.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [4.5], "angulation_deg": 0,
     "torque_ncm": 35, "catalog_code": "062.47255",
     "indication": "Pro Arch multi-unit, parallel implant"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 17° angled, GH 3.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 17,
     "torque_ncm": 35, "catalog_code": "062.47335",
     "indication": "Pro Arch, mild divergence"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 17° angled, GH 4.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [4.5], "angulation_deg": 17,
     "torque_ncm": 35, "catalog_code": "062.47345",
     "indication": "Pro Arch, mild divergence"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 17° angled, GH 5.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [5.5], "angulation_deg": 17,
     "torque_ncm": 35, "catalog_code": "062.47355",
     "indication": "Pro Arch, mild divergence"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 30° angled, GH 3.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [3.5], "angulation_deg": 30,
     "torque_ncm": 35, "catalog_code": "062.47435",
     "indication": "Pro Arch, severe divergence (tilted posterior)"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 30° angled, GH 4.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [4.5], "angulation_deg": 30,
     "torque_ncm": 35, "catalog_code": "062.47445",
     "indication": "Pro Arch, severe divergence (tilted posterior)"},
    {"type": "screw_retained_abutment", "subtype": "RB SRA, 30° angled, GH 5.5 (sterile)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 4.6, "gingival_heights_mm": [5.5], "angulation_deg": 30,
     "torque_ncm": 35, "catalog_code": "062.47455",
     "indication": "Pro Arch, severe divergence (tilted posterior)"},

    # ── Impression posts at implant level (RB/WB shared) ─────────────────
    {"type": "impression_post", "subtype": "RB/WB Impression Post Open-tray, short (16.5 mm)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 16.5, "catalog_code": "065.0031",
     "indication": "Open-tray impression at implant level"},
    {"type": "impression_post", "subtype": "RB/WB Impression Post Closed-tray, long (24 mm)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 24, "catalog_code": "065.0033",
     "indication": "Closed-tray impression at implant level"},
    {"type": "impression_post", "subtype": "RB/WB Impression Post Closed-tray (13 mm)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 13, "catalog_code": "065.4310",
     "indication": "Closed-tray impression at implant level"},
    {"type": "scan_body", "subtype": "RB/WB CARES® Mono Scanbody",
     "platform": "RB", "material": ["PEEK", "TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "abutment_height_mm": 10, "catalog_code": "065.0035",
     "indication": "Intra-oral digital scanning"},
    {"type": "scan_body", "subtype": "ScanPost S RB/WB L (Sirona)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "catalog_code": "065.0038",
     "indication": "Sirona CEREC scanbody"},
    {"type": "implant_analog", "subtype": "RB Repositionable Implant Analog (digital)",
     "platform": "RB", "material": ["stainless_steel"], "retention": [],
     "abutment_height_mm": 17, "catalog_code": "065.0023",
     "indication": "Repositionable analog for fully digital workflow"},
    {"type": "implant_analog", "subtype": "RB Implant Analog",
     "platform": "RB", "material": ["TAN"], "retention": [],
     "abutment_height_mm": 12, "catalog_code": "065.0021",
     "indication": "Stone-model analog"},

    # ── Pre-milled blanks ─────────────────────────────────────────────────
    {"type": "premilled_blank", "subtype": "RB Pre-milled Abutment Blank, Medentika Ø11.5",
     "platform": "RB", "material": ["TAN"], "catalog_code": "062.4601",
     "indication": "Custom CAD/CAM abutment, Medentika holder"},
    {"type": "premilled_blank", "subtype": "RB Pre-milled Abutment Blank, Medentika Ø15.8",
     "platform": "RB", "material": ["TAN"], "catalog_code": "062.4602",
     "indication": "Custom CAD/CAM abutment (wider), Medentika holder"},
    {"type": "premilled_blank", "subtype": "RB Pre-milled Abutment Blank, CARES® Ø12",
     "platform": "RB", "material": ["TAN"], "catalog_code": "062.4603",
     "indication": "Custom CAD/CAM abutment, Straumann CARES® holder"},

    # ── Replacement screws (RB/WB shared) ────────────────────────────────
    {"type": "replacement_screw", "subtype": "RB/WB Basal Screw",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 6.1, "torque_ncm": 35, "catalog_code": "065.0036",
     "indication": "Final abutment fixation (Temp / Anatomic / Variobase / Gold / Pre-milled / angled SRA / angled Novaloc)"},
    {"type": "replacement_screw", "subtype": "RB/WB Basal Screw AS (green color-coded)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 6.5, "torque_ncm": 35, "catalog_code": "065.0037",
     "indication": "For Variobase® Crown AS only — requires AS Screwdriver"},
    {"type": "replacement_screw", "subtype": "Occlusal Screw (for SRA copings)",
     "platform": "RB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 3.7, "torque_ncm": 15, "catalog_code": "023.4763",
     "indication": "Titanium / Gold / Burn-out / Variobase® SRA copings"},
]


# ── WB Platform components (extends RB with WB-only SKUs from pages 25-29) ──
_WB_COMPONENTS: List[Dict] = [
    # Cover screw (implicit)
    {"type": "cover_screw", "subtype": "WB Closure Screw",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "torque_ncm": 15, "catalog_code": "—",
     "indication": "Submerged two-stage healing (included with WB implant kit)"},

    # ── WB Impression posts (page 25) ────────────────────────────────────
    {"type": "impression_post", "subtype": "WB Impression Post Open-tray, short (16.5 mm)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 16.5, "catalog_code": "065.0032",
     "indication": "Open-tray impression on WB implant"},
    {"type": "impression_post", "subtype": "WB Impression Post Closed-tray, long (24 mm)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 24, "catalog_code": "065.0034",
     "indication": "Closed-tray impression on WB implant"},
    {"type": "impression_post", "subtype": "WB Impression Post Closed-tray (13 mm)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 13, "catalog_code": "065.4810",
     "indication": "Closed-tray impression on WB implant"},
    {"type": "scan_body", "subtype": "RB/WB CARES® Mono Scanbody",
     "platform": "WB", "material": ["PEEK", "TAN"], "retention": ["screw"],
     "diameter_mm": 3.8, "abutment_height_mm": 10, "catalog_code": "065.0035",
     "indication": "Intra-oral digital scanning"},
    {"type": "scan_body", "subtype": "ScanPost S RB/WB L (Sirona)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "catalog_code": "065.0038",
     "indication": "Sirona CEREC scanbody — WB compatible"},
    {"type": "implant_analog", "subtype": "WB Repositionable Implant Analog (digital)",
     "platform": "WB", "material": ["stainless_steel"], "retention": [],
     "abutment_height_mm": 17, "catalog_code": "065.0024",
     "indication": "Repositionable analog for fully digital workflow"},
    {"type": "implant_analog", "subtype": "WB Implant Analog",
     "platform": "WB", "material": ["TAN"], "retention": [],
     "abutment_height_mm": 12, "catalog_code": "065.0022",
     "indication": "Stone-model analog — WB"},

    # ── WB Healing Abutments — GH 0.75 series (page 26) ──────────────────
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø6, GH 0.75, H 2",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [0.75], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.82015",
     "indication": "Transmucosal healing — thin gingiva"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø6, GH 0.75, H 4",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [0.75], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.82025",
     "indication": "Transmucosal healing — thin gingiva"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø7.5, GH 0.75, H 2",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 7.5, "gingival_heights_mm": [0.75], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.82035",
     "indication": "Transmucosal healing — thin gingiva, wide emergence"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø7.5, GH 0.75, H 4",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 7.5, "gingival_heights_mm": [0.75], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.82045",
     "indication": "Transmucosal healing — thin gingiva, wide emergence"},
    # WB Healing Abutments — GH 1.5 series
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø6, GH 1.5, H 2",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.82125",
     "indication": "Transmucosal healing"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø6, GH 1.5, H 4",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 6.0, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.82135",
     "indication": "Transmucosal healing"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø7.5, GH 1.5, H 2",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 7.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 2,
     "torque_ncm": 15, "catalog_code": "064.82145",
     "indication": "Transmucosal healing — wide emergence"},
    {"type": "healing_abutment", "subtype": "WB Healing Abutment Ø7.5, GH 1.5, H 4",
     "platform": "WB", "material": ["titanium"], "retention": ["screw"],
     "diameter_mm": 7.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 4,
     "torque_ncm": 15, "catalog_code": "064.82155",
     "indication": "Transmucosal healing — wide emergence"},

    # ── WB Temporary abutments (page 27) ─────────────────────────────────
    {"type": "temporary_abutment", "subtype": "WB Temporary Abutment Ø5.5, GH 0.75",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [0.75], "torque_ncm": 15,
     "catalog_code": "064.4391", "indication": "Provisional crown — WB"},
    {"type": "temporary_abutment", "subtype": "WB Temporary Abutment Ø5.5, GH 1.5",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [1.5], "torque_ncm": 15,
     "catalog_code": "064.4392", "indication": "Provisional crown — WB"},

    # ── WB Variobase® (page 27) ──────────────────────────────────────────
    {"type": "ti_base", "subtype": "WB Variobase® Crown Ø5.5, GH 0.75",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [0.75], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4953",
     "indication": "CAD/CAM crown — WB thin gingiva"},
    {"type": "ti_base", "subtype": "WB Variobase® Crown Ø5.5, GH 1.5",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "torque_ncm": 35, "catalog_code": "062.4954",
     "indication": "CAD/CAM crown — WB"},
    {"type": "ti_base", "subtype": "WB Variobase® C Ø5.5, GH 1.5 (Sirona)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.4983",
     "indication": "Variobase® C for Sirona CEREC — WB"},
    {"type": "ti_base", "subtype": "WB Variobase® Crown AS Ø5.5, GH 1.5",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "diameter_mm": 5.5, "gingival_heights_mm": [1.5], "abutment_height_mm": 5.5,
     "angulation_deg": 25, "torque_ncm": 35, "catalog_code": "062.4971",
     "indication": "Angulated Screw Channel up to 25° — WB"},

    # ── WB Burn-out copings (page 27) ────────────────────────────────────
    {"type": "burnout_coping", "subtype": "WB Burn-out Coping for Variobase® Crown Ø5.5",
     "platform": "WB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 5.5, "abutment_height_mm": 5.5, "catalog_code": "065.0016",
     "indication": "Cast-on crown framework — WB"},
    {"type": "burnout_coping", "subtype": "WB Burn-out Coping AS Crown Ø5.5",
     "platform": "WB", "material": ["POM"], "retention": ["screw"],
     "diameter_mm": 5.5, "abutment_height_mm": 5.5, "angulation_deg": 25,
     "catalog_code": "065.0019",
     "indication": "Angulated Screw Channel cast-on framework — WB"},

    # ── WB Gold abutment (page 28) ───────────────────────────────────────
    {"type": "final_abutment", "subtype": "WB Gold Abutment Crown Ø5.5, GH 1.5",
     "platform": "WB", "material": ["Ceramicor", "POM"], "retention": ["cement"],
     "diameter_mm": 5.5, "gingival_heights_mm": [1.5], "torque_ncm": 35,
     "catalog_code": "062.8410",
     "indication": "Cast-on crown, incl. screw 065.0036"},

    # ── WB Pre-milled blanks (page 29) ───────────────────────────────────
    {"type": "premilled_blank", "subtype": "WB Pre-milled Abutment Blank, Medentika Ø11.5",
     "platform": "WB", "material": ["TAN"], "catalog_code": "062.4605",
     "indication": "Custom CAD/CAM abutment — WB, Medentika holder"},
    {"type": "premilled_blank", "subtype": "WB Pre-milled Abutment Blank, Medentika Ø15.8",
     "platform": "WB", "material": ["TAN"], "catalog_code": "062.4606",
     "indication": "Custom CAD/CAM abutment wider — WB, Medentika holder"},
    {"type": "premilled_blank", "subtype": "WB Pre-milled Abutment Blank, CARES® Ø12",
     "platform": "WB", "material": ["TAN"], "catalog_code": "062.4607",
     "indication": "Custom CAD/CAM abutment — WB, CARES® holder"},

    # ── Replacement screws (RB/WB shared, surfaced in WB list too) ──────
    {"type": "replacement_screw", "subtype": "RB/WB Basal Screw",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 6.1, "torque_ncm": 35, "catalog_code": "065.0036",
     "indication": "Final abutment fixation (Temp / Anatomic / Variobase / Gold / Pre-milled / angled SRA / angled Novaloc)"},
    {"type": "replacement_screw", "subtype": "RB/WB Basal Screw AS (green color-coded)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 6.5, "torque_ncm": 35, "catalog_code": "065.0037",
     "indication": "For WB Variobase® Crown AS only — requires AS Screwdriver"},
    {"type": "replacement_screw", "subtype": "Occlusal Screw (for SRA copings)",
     "platform": "WB", "material": ["TAN"], "retention": ["screw"],
     "abutment_height_mm": 3.7, "torque_ncm": 15, "catalog_code": "023.4763",
     "indication": "Titanium / Gold / Burn-out / Variobase® SRA copings"},
]


# Per-platform component palettes (RB extended with shared SRA + Novaloc lists).
COMPONENTS_BY_PLATFORM: Dict[str, List[Dict]] = {
    "RB": _RB_COMPONENTS + _SRA_SHARED + _NOVALOC_SHARED,
    "WB": _WB_COMPONENTS + _SRA_SHARED,  # Novaloc is primarily RB-Ø3.8
}


# Map each Straumann BLX system to its prosthetic platform.
SYSTEM_PLATFORM: Dict[str, str] = {
    "BLX Roxolid SLActive - RB Platform": "RB",
    "BLX Roxolid SLA - RB Platform": "RB",
    "BLX Roxolid SLActive - WB Platform": "WB",
    "BLX Roxolid SLA - WB Platform": "WB",
}


def expanded_components_for(system_name: str) -> List[Dict]:
    """Return a fresh deep-copyable component list for a Straumann BLX system."""
    import copy
    platform = SYSTEM_PLATFORM.get(system_name)
    if platform is None:
        return []
    return copy.deepcopy(COMPONENTS_BY_PLATFORM[platform])
