export type DentalCollege = {
  name: string;
  state: string;
  type: 'Govt' | 'Private';
};

// Source: Dental Council of India (DCI) — 330 recognised dental colleges, AY 2025-26
export const DENTAL_COLLEGES: DentalCollege[] = [
  // Andhra Pradesh
  { name: 'Anil Neerukonda Institute of Dental Sciences, Visakhapatnam', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'C.K.S. Teja Institute of Dental Sciences & Research, Tirupati', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Care Dental College, Guntur', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Drs. Sudha & Nageswara Rao Siddhartha Institute of Dental Sciences, Gannavaram Mandalam', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'G. Pulla Reddy Dental College & Hospital, Kurnool', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Gitam Dental College & Hospital, Vishakhapatnam', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Govt. Dental College & Hospital, Vijayawada', state: 'Andhra Pradesh', type: 'Govt' },
  { name: 'Govt. Dental College, RIMS, Kadapa', state: 'Andhra Pradesh', type: 'Govt' },
  { name: 'GSL Dental College & Hospital, Rajahmundry', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'KIMS Dental College, Amalapuram', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Lenora Institute of Dental Sciences, Rajahmundry', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Narayana Dental College & Hospital, Nellore', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Nimra Institute of Dental Sciences', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Sibar Institute of Dental Sciences, Guntur', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Sree Sai Dental College & Research Institute, Srikakulam', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'St. Joseph Dental College, Duggirala', state: 'Andhra Pradesh', type: 'Private' },
  { name: 'Vishnu Dental College, Bhimavaram', state: 'Andhra Pradesh', type: 'Private' },
  // Assam
  { name: 'Govt. Dental College, Dibrugarh', state: 'Assam', type: 'Govt' },
  { name: 'Govt. Dental College, Silchar', state: 'Assam', type: 'Govt' },
  { name: 'Regional Dental College, Guwahati', state: 'Assam', type: 'Govt' },
  // Bihar
  { name: 'Buddha Institute of Dental Sciences & Hospital, Patna', state: 'Bihar', type: 'Private' },
  { name: 'Government Dental College & Hospital, Nalanda', state: 'Bihar', type: 'Govt' },
  { name: 'Mithila Minority Dental College & Hospital, Darbhanga', state: 'Bihar', type: 'Private' },
  { name: 'Patna Dental College & Hospital, Patna', state: 'Bihar', type: 'Govt' },
  { name: 'Sarjug Dental College, Darbhanga', state: 'Bihar', type: 'Private' },
  // Chandigarh
  { name: 'Dr. Harvansh Singh Judge Institute of Dental Sciences & Hospital, Chandigarh', state: 'Chandigarh', type: 'Govt' },
  // Chhattisgarh
  { name: 'Chattisgarh Dental College & Research Institute, Rajnandgaon', state: 'Chhattisgarh', type: 'Private' },
  { name: 'Govt. Dental College, Raipur', state: 'Chhattisgarh', type: 'Govt' },
  { name: 'Maitri College of Dentistry and Research Centre, Durg', state: 'Chhattisgarh', type: 'Private' },
  { name: 'New Horizon Dental College & Research Institute, Bilaspur', state: 'Chhattisgarh', type: 'Private' },
  { name: 'Rungta College of Dental Sciences & Research, Bhilai', state: 'Chhattisgarh', type: 'Private' },
  { name: 'Shri Balaji Institute of Dental Sciences, Raipur', state: 'Chhattisgarh', type: 'Private' },
  { name: 'Triveni Institute of Dental Sciences, Hospital & Research Centre, Bilaspur', state: 'Chhattisgarh', type: 'Private' },
  // Daman & Diu
  { name: 'Vaidik Dental College and Research Centre', state: 'Dadra & Nagar Haveli and Daman & Diu', type: 'Private' },
  // Delhi
  { name: 'Army Hospital (Research and Referral) Delhi Cantt', state: 'Delhi', type: 'Govt' },
  { name: 'ESIC Dental College, Rohini, New Delhi', state: 'Delhi', type: 'Govt' },
  { name: 'Faculty of Dentistry, Jamia Millia Islamia, New Delhi', state: 'Delhi', type: 'Govt' },
  { name: 'Lady Hardinge Medical College, New Delhi', state: 'Delhi', type: 'Govt' },
  { name: 'Maulana Azad Dental College & Hospital, New Delhi', state: 'Delhi', type: 'Govt' },
  { name: 'University College of Medical Sciences, Dilshad Garden', state: 'Delhi', type: 'Govt' },
  // Goa
  { name: 'Goa Dental College & Hospital, Goa', state: 'Goa', type: 'Govt' },
  // Gujarat
  { name: 'Ahmedabad Dental College & Hospital, Gandhinagar', state: 'Gujarat', type: 'Private' },
  { name: 'AMC Dental College, Ahmedabad', state: 'Gujarat', type: 'Govt' },
  { name: 'College of Dental Sciences and Research Centre, Ahmedabad', state: 'Gujarat', type: 'Private' },
  { name: 'College of Dental Sciences, Amargadh', state: 'Gujarat', type: 'Private' },
  { name: 'Faculty of Dental Science, Dharmsinh Desai University, Nadiad', state: 'Gujarat', type: 'Private' },
  { name: 'Goenka Research Institute of Dental Sciences, Gandhinagar', state: 'Gujarat', type: 'Private' },
  { name: 'Govt. Dental College & Hospital, Ahmedabad', state: 'Gujarat', type: 'Govt' },
  { name: 'Govt. Dental College Hospital, Jamnagar', state: 'Gujarat', type: 'Govt' },
  { name: 'K.M. Shah Dental College & Hospital, Vadodara', state: 'Gujarat', type: 'Private' },
  { name: 'Karnavati School of Dentistry, Gandhinagar', state: 'Gujarat', type: 'Private' },
  { name: 'Manubhai Patel Dental College & Dental Hospital, Vadodara', state: 'Gujarat', type: 'Private' },
  { name: 'Narsinhbhai Patel Dental College & Hospital, Visnagar', state: 'Gujarat', type: 'Private' },
  { name: 'Siddhpur Dental College, Patan', state: 'Gujarat', type: 'Govt' },
  // Haryana
  { name: 'D.A.V. Centenary Dental College, Yamuna Nagar', state: 'Haryana', type: 'Private' },
  { name: 'Jan Nayak Ch. Devi Lal Dental College, Sirsa', state: 'Haryana', type: 'Private' },
  { name: 'Maharishi Markandeshwar College of Dental Sciences & Research, Mullana', state: 'Haryana', type: 'Private' },
  { name: 'Manav Rachana Dental College, Faridabad', state: 'Haryana', type: 'Private' },
  { name: 'PDM Dental College & Research Institute, Jhajjar', state: 'Haryana', type: 'Private' },
  { name: 'Post Graduate Institute of Dental Sciences, Rohtak', state: 'Haryana', type: 'Govt' },
  { name: 'Sri Govind Tricentenary Dental College, Hospital & Research Institute', state: 'Haryana', type: 'Private' },
  { name: 'Sudha Rustagi College of Dental Sciences & Research, Faridabad', state: 'Haryana', type: 'Private' },
  { name: 'Swami Devi Dyal Hospital & Dental College, Panchkula', state: 'Haryana', type: 'Private' },
  { name: 'Yamuna Institute of Dental Sciences & Research, Yamuna Nagar', state: 'Haryana', type: 'Private' },
  // Himachal Pradesh
  { name: 'Bhojia Dental College & Hospital, Nalagarh', state: 'Himachal Pradesh', type: 'Private' },
  { name: 'H.P. Govt. Dental College & Hospital, Shimla', state: 'Himachal Pradesh', type: 'Govt' },
  { name: 'Himachal Dental College, Sunder Nagar', state: 'Himachal Pradesh', type: 'Private' },
  { name: 'Himachal Institute of Dental Sciences, Poanta Sahib', state: 'Himachal Pradesh', type: 'Private' },
  { name: 'M.N.D.A.V. Dental College & Hospital, Solan', state: 'Himachal Pradesh', type: 'Private' },
  // Jammu & Kashmir
  { name: 'Govt. Dental College, Srinagar', state: 'Jammu & Kashmir', type: 'Govt' },
  { name: 'Indira Gandhi Government Dental College, Jammu', state: 'Jammu & Kashmir', type: 'Govt' },
  { name: 'Institute of Dental Sciences, Sehora', state: 'Jammu & Kashmir', type: 'Private' },
  // Jharkhand
  { name: 'Awadh Dental College & Hospital, Jamshedpur', state: 'Jharkhand', type: 'Private' },
  { name: 'Dental Institute Rajendra Institute of Medical Sciences, Ranchi', state: 'Jharkhand', type: 'Govt' },
  { name: 'Hazaribag College of Dental Sciences and Hospital, Hazaribag', state: 'Jharkhand', type: 'Private' },
  { name: 'Vananchal Dental College & Hospital, Garhwa', state: 'Jharkhand', type: 'Private' },
  // Karnataka
  { name: 'A.B. Shetty Memorial Institute of Dental Sciences, Mangalore', state: 'Karnataka', type: 'Private' },
  { name: 'A.J. Institute of Dental Sciences, Mangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Al Ameen Dental College & Hospital, Bijapur', state: 'Karnataka', type: 'Private' },
  { name: 'Al-Badar Rural Dental College & Hospital, Gulbarga', state: 'Karnataka', type: 'Private' },
  { name: "AME's Dental College & Hospital, Raichur", state: 'Karnataka', type: 'Private' },
  { name: 'Bangalore Institute of Dental Sciences & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Bapuji Dental College & Hospital, Davangere', state: 'Karnataka', type: 'Private' },
  { name: 'BGS Global Institute of Dental Sciences and Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'College of Dental Sciences, Davangere', state: 'Karnataka', type: 'Private' },
  { name: 'Coorg Institute of Dental Sciences, Virajpat', state: 'Karnataka', type: 'Private' },
  { name: 'D.A. Pandu Memorial R.V. Dental College, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Dayanand Sagar College of Dental Sciences, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Dr. Syamala Reddy Dental College, Hospital & Research Centre, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'ESIC Dental College, Gulbarga', state: 'Karnataka', type: 'Govt' },
  { name: 'Farooqia Dental College & Hospital, Mysore', state: 'Karnataka', type: 'Private' },
  { name: 'Govt. Dental College & Research Institute, Bellary', state: 'Karnataka', type: 'Govt' },
  { name: 'Govt. Dental College, Bangalore', state: 'Karnataka', type: 'Govt' },
  { name: 'H.K.D.E.Ts Dental College, Hospital & Research Institute, Humnabad', state: 'Karnataka', type: 'Private' },
  { name: "H.K.E. Society's, S. Nijalingappa Institute of Dental Sciences & Research", state: 'Karnataka', type: 'Private' },
  { name: 'JSS Dental College & Hospital, Mysore', state: 'Karnataka', type: 'Private' },
  { name: 'K.G.F. College of Dental Sciences & Hospital, KGF', state: 'Karnataka', type: 'Private' },
  { name: 'K.V.G. Dental College & Hospital, Sullia', state: 'Karnataka', type: 'Private' },
  { name: "KLE Society's Institute of Dental Sciences, Bangalore", state: 'Karnataka', type: 'Private' },
  { name: 'KLE Vishwanath Katti Institute of Dental Sciences, Belgaum', state: 'Karnataka', type: 'Private' },
  { name: 'Krishnadevaraya College of Dental Sciences & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'M.R. Ambedkar Dental College & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'M.S. Ramaiah Dental College, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Manipal College of Dental Sciences, Mangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Manipal College of Dental Sciences, Manipal', state: 'Karnataka', type: 'Private' },
  { name: "Maratha Mandal's Dental College & Research Centre, Belgaum", state: 'Karnataka', type: 'Private' },
  { name: 'Navodaya Dental College, Raichur', state: 'Karnataka', type: 'Private' },
  { name: 'P.M.N.M. Dental College & Hospital, Bagalkot', state: 'Karnataka', type: 'Private' },
  { name: 'Rajarajeswari Dental College & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'S.B. Patil Dental College & Hospital, Bidar', state: 'Karnataka', type: 'Private' },
  { name: 'S.J.M. Dental College & Hospital, Chitradurga', state: 'Karnataka', type: 'Private' },
  { name: 'SDM College of Dental Sciences & Hospital, Dharwad', state: 'Karnataka', type: 'Private' },
  { name: 'Sharavathi Dental College & Hospital, Shimoga', state: 'Karnataka', type: 'Private' },
  { name: 'Sri Hasanamba Dental College & Hospital, Hassan', state: 'Karnataka', type: 'Private' },
  { name: 'Sri Rajiv Gandhi College of Dental Sciences & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Sri Siddhartha Dental College, Tumkur', state: 'Karnataka', type: 'Private' },
  { name: 'Sri Venkateshwara Dental College & Hospital, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Srinivas Institute of Dental Sciences, Mangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Subbaiah Institute of Dental Sciences, Purale, Shimoga', state: 'Karnataka', type: 'Private' },
  { name: 'The Oxford Dental College, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'V.S. Dental College, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Vydehi Institute of Dental Sciences & Research, Bangalore', state: 'Karnataka', type: 'Private' },
  { name: 'Yenepoya Dental College & Hospital, Mangalore', state: 'Karnataka', type: 'Private' },
  // Kerala
  { name: 'Al-Azhar Dental College, Kerala', state: 'Kerala', type: 'Private' },
  { name: 'Amrita School of Dentistry, Kochi', state: 'Kerala', type: 'Private' },
  { name: 'Annoor Dental College & Hospital, Ernakulam', state: 'Kerala', type: 'Private' },
  { name: 'Azeezia College of Dental Sciences & Research, Kollam', state: 'Kerala', type: 'Private' },
  { name: 'Century International Institute of Dental Science & Research Center, Kasaragod', state: 'Kerala', type: 'Private' },
  { name: 'Educare Institute of Dental Sciences, Malappuram', state: 'Kerala', type: 'Private' },
  { name: 'Govt. Dental College, Alappuzha', state: 'Kerala', type: 'Govt' },
  { name: 'Govt. Dental College, Kottayam', state: 'Kerala', type: 'Govt' },
  { name: 'Govt. Dental College, Kozhikode', state: 'Kerala', type: 'Govt' },
  { name: 'Govt. Dental College, Thrissur', state: 'Kerala', type: 'Govt' },
  { name: 'Govt. Dental College, Trivandrum', state: 'Kerala', type: 'Govt' },
  { name: 'Indira Gandhi Institute of Dental Sciences, Kothamangalam', state: 'Kerala', type: 'Private' },
  { name: 'Kannur Dental College, Kannur', state: 'Kerala', type: 'Private' },
  { name: 'KMCT Dental College, Calicut', state: 'Kerala', type: 'Private' },
  { name: 'Malabar Dental College & Research Centre, Malappuram', state: 'Kerala', type: 'Private' },
  { name: 'Mar Baselios Dental College, Kothamangalam', state: 'Kerala', type: 'Private' },
  { name: 'MES Dental College, Malappuram', state: 'Kerala', type: 'Private' },
  { name: 'Noorul Islam College of Dental Sciences, Trivandrum', state: 'Kerala', type: 'Private' },
  { name: 'Pariyaram Dental College, Academy of Medical Sciences, Kannur', state: 'Kerala', type: 'Govt' },
  { name: 'PMS College of Dental Science & Research, Thiruvananthapuram', state: 'Kerala', type: 'Private' },
  { name: 'PSM College of Dental Sciences & Research, Trichur', state: 'Kerala', type: 'Private' },
  { name: 'Pushpagiri College of Dental Sciences, Tiruvalla', state: 'Kerala', type: 'Private' },
  { name: 'Royal Dental College, Kerala', state: 'Kerala', type: 'Private' },
  { name: 'Sree Anjaneya Medical Trust, Calicut', state: 'Kerala', type: 'Private' },
  { name: 'Sri Sankara Dental College, Thiruvananthapuram', state: 'Kerala', type: 'Private' },
  { name: 'St. Gregorios Dental College, Ernakulam', state: 'Kerala', type: 'Private' },
  { name: 'Travancore Dental College', state: 'Kerala', type: 'Private' },
  // Madhya Pradesh
  { name: 'Bhabha College of Dental Sciences, Bhopal', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'College of Dental Sciences & Hospital, Indore', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'College of Dentistry, Indore', state: 'Madhya Pradesh', type: 'Govt' },
  { name: 'Guru Gobind Singh College of Dental Science & Research Centre, Burhanpur', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Hitkarini Dental College & Hospital, Jabalpur', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Index Institute of Dental Sciences, Indore', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Maharana Pratap College of Dentistry & Research Centre, Gwalior', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Mansarover Dental College, Bhopal', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Modern Dental College & Research Centre, Indore', state: 'Madhya Pradesh', type: 'Private' },
  { name: "People's Dental Academy, Bhopal", state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Peoples College of Dental Sciences & Research Centre, Bhopal', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Rishiraj College of Dental Sciences & Research Centre, Bhopal', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'RKDF Dental College & Research Centre, Bhopal', state: 'Madhya Pradesh', type: 'Private' },
  { name: 'Sri Aurobindo College of Dentistry, Indore', state: 'Madhya Pradesh', type: 'Private' },
  // Maharashtra
  { name: 'Aditya Dental College, Beed', state: 'Maharashtra', type: 'Private' },
  { name: 'Annasaheb Chudaman Patil Memorial Dental College, Dhule', state: 'Maharashtra', type: 'Private' },
  { name: 'Armed Forces Medical College, Pune', state: 'Maharashtra', type: 'Govt' },
  { name: 'Bharati Vidyapeeth Dental College & Hospital, Navi Mumbai', state: 'Maharashtra', type: 'Private' },
  { name: 'Bharati Vidyapeeth Dental College & Hospital, Pune', state: 'Maharashtra', type: 'Private' },
  { name: 'Bharati Vidyapeeth Dental College & Hospital, Sangli', state: 'Maharashtra', type: 'Private' },
  { name: "Chatrapati Shahu Maharaj Shikshan Sanstha's Dental College & Hospital, Aurangabad", state: 'Maharashtra', type: 'Private' },
  { name: 'D.Y. Patil Dental School, Pune', state: 'Maharashtra', type: 'Private' },
  { name: 'Dr. D.Y. Patil Dental College & Hospital, Pune', state: 'Maharashtra', type: 'Private' },
  { name: 'Dr. Hedgewar Smruti Rugna Seva Mandals Dental College & Hospital, Hingoli', state: 'Maharashtra', type: 'Private' },
  { name: 'Dr. Rajesh Ramdasji Kambe Dental College & Hospital, Akola', state: 'Maharashtra', type: 'Private' },
  { name: 'Govt. Dental College & Hospital, Aurangabad', state: 'Maharashtra', type: 'Govt' },
  { name: 'Govt. Dental College & Hospital, Jalgaon', state: 'Maharashtra', type: 'Govt' },
  { name: 'Govt. Dental College & Hospital, Mumbai', state: 'Maharashtra', type: 'Govt' },
  { name: 'Govt. Dental College & Hospital, Nagpur', state: 'Maharashtra', type: 'Govt' },
  { name: "Late Shri Yashwantrao Chavan Memorial Medical & Rural Development Foundation's Dental College & Hospital, Ahmednagar", state: 'Maharashtra', type: 'Private' },
  { name: 'M.A. Rangoonwala College of Dental Sciences & Research Centre, Pune', state: 'Maharashtra', type: 'Private' },
  { name: 'Maharashtra Institute of Dental Sciences & Research', state: 'Maharashtra', type: 'Private' },
  { name: 'Mahatma Gandhi Missions Dental College & Hospital, Navi Mumbai', state: 'Maharashtra', type: 'Private' },
  { name: "Mahatma Gandhi Vidya Mandir's Dental College & Hospital, Nashik", state: 'Maharashtra', type: 'Private' },
  { name: 'Nair Hospital Dental College, Mumbai', state: 'Maharashtra', type: 'Govt' },
  { name: 'Nanded Rural Dental College & Research Center, Nanded', state: 'Maharashtra', type: 'Private' },
  { name: 'Padmashree Dr. D.Y. Patil Dental College & Hospital, Navi Mumbai', state: 'Maharashtra', type: 'Private' },
  { name: 'Pandit Dindayal Upadhyay Dental College, Solapur', state: 'Maharashtra', type: 'Private' },
  { name: 'Ranjeet Deshmukh Dental College and Research Centre, Nagpur', state: 'Maharashtra', type: 'Private' },
  { name: 'Rural Dental College, Loni', state: 'Maharashtra', type: 'Private' },
  { name: 'S.M.B.T. Dental College & Hospital, Amrutnagar', state: 'Maharashtra', type: 'Private' },
  { name: 'Saraswati Danwantri Dental College & Hospital, Parbhani', state: 'Maharashtra', type: 'Private' },
  { name: 'School of Dental Sciences, Krishna Institute of Medical Sciences, Karad', state: 'Maharashtra', type: 'Private' },
  { name: 'Sharad Pawar Dental College & Hospital, Wardha', state: 'Maharashtra', type: 'Private' },
  { name: 'Sinhgad Dental College & Hospital, Pune', state: 'Maharashtra', type: 'Private' },
  { name: 'SMBT Institute of Dental Sciences and Research, Nashik', state: 'Maharashtra', type: 'Private' },
  { name: 'Swargiya Dadasaheb Kalmegh Smruti Dental College & Hospital, Nagpur', state: 'Maharashtra', type: 'Private' },
  { name: 'Tatyasaheb Kore Dental College & Research Centre, New Pargaon', state: 'Maharashtra', type: 'Private' },
  { name: 'Terna Dental College & Hospital, Navi Mumbai', state: 'Maharashtra', type: 'Private' },
  { name: 'Vasantdada Patil Dental College and Hospital, Sangli', state: 'Maharashtra', type: 'Private' },
  { name: "Vidarbha Youth Welfare Society's Dental College & Hospital, Amravati", state: 'Maharashtra', type: 'Private' },
  { name: "Yerala Medical Trust & Research Centre's Dental College & Hospital, Navi Mumbai", state: 'Maharashtra', type: 'Private' },
  { name: 'Yogita Dental College & Hospital, Ratnagiri', state: 'Maharashtra', type: 'Private' },
  // Manipur
  { name: 'Dental College, Jawaharlal Nehru Institute of Medical Sciences', state: 'Manipur', type: 'Govt' },
  { name: 'Dental College, RIMS, Imphal', state: 'Manipur', type: 'Govt' },
  // Odisha
  { name: 'Hi-Tech Dental College & Hospital, Bhubaneswar', state: 'Odisha', type: 'Private' },
  { name: 'Institute of Dental Sciences, Bhubaneswar', state: 'Odisha', type: 'Private' },
  { name: 'Kalinga Institute of Dental Sciences, Bhubaneswar', state: 'Odisha', type: 'Private' },
  { name: 'S.C.B. Dental College & Hospital, Cuttack', state: 'Odisha', type: 'Govt' },
  // Puducherry
  { name: 'Indira Gandhi Institute of Dental Sciences, Pondicherry', state: 'Puducherry', type: 'Private' },
  { name: 'Mahatma Gandhi Post Graduate Institute of Dental Sciences, Puducherry', state: 'Puducherry', type: 'Govt' },
  { name: 'Mahe Institute of Dental Sciences & Hospital, Mahe', state: 'Puducherry', type: 'Private' },
  { name: 'Sri Venkateshwaraa Dental College, Puducherry', state: 'Puducherry', type: 'Private' },
  // Punjab
  { name: 'Adesh Institute of Dental Sciences & Research, Bathinda', state: 'Punjab', type: 'Private' },
  { name: 'Baba Jaswant Singh Dental College Hospital & Research Institute, Ludhiana', state: 'Punjab', type: 'Private' },
  { name: 'Christian Dental College, Ludhiana', state: 'Punjab', type: 'Private' },
  { name: 'Dasmesh Institute of Research & Dental Sciences, Faridkot', state: 'Punjab', type: 'Private' },
  { name: 'Desh Bhagat Dental College & Hospital, Mandi Gobindgarh', state: 'Punjab', type: 'Private' },
  { name: 'Genesis Institute of Dental Sciences & Research, Ferozepur', state: 'Punjab', type: 'Private' },
  { name: 'Gian Sagar Dental College & Hospital', state: 'Punjab', type: 'Private' },
  { name: 'Govt. Dental College & Hospital, Patiala', state: 'Punjab', type: 'Govt' },
  { name: 'Guru Nanak Dev Dental College & Research Institute, Sunam', state: 'Punjab', type: 'Private' },
  { name: 'Luxmi Bai Institute of Dental Sciences & Hospital, Patiala', state: 'Punjab', type: 'Private' },
  { name: 'National Dental College & Hospital, Gulabgarh', state: 'Punjab', type: 'Private' },
  { name: 'Pb. Govt. Dental College & Hospital, Amritsar', state: 'Punjab', type: 'Govt' },
  { name: 'Rayat Bahra Dental College, Mohali', state: 'Punjab', type: 'Private' },
  { name: 'Shaheed Kartar Singh Sarabha Dental College & Hospital, Ludhiana', state: 'Punjab', type: 'Private' },
  { name: 'Sri Guru Ram Das Institute of Dental Sciences & Research, Amritsar', state: 'Punjab', type: 'Private' },
  { name: 'Sukhmani Dental College & Hospital, Derabassi', state: 'Punjab', type: 'Private' },
  // Rajasthan
  { name: 'Darshan Dental College & Hospital, Udaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Daswani Dental College & Research Centre, Kota', state: 'Rajasthan', type: 'Private' },
  { name: 'Dr. S. S. Tantia Dental College Hospital and Research Centre', state: 'Rajasthan', type: 'Private' },
  { name: 'Eklavya Dental College & Hospital, Kotputli', state: 'Rajasthan', type: 'Private' },
  { name: 'Geetanjali Dental & Research Institute, Udaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Government Dental College, Jodhpur', state: 'Rajasthan', type: 'Govt' },
  { name: 'Govt. Dental College & Hospital, Jaipur', state: 'Rajasthan', type: 'Govt' },
  { name: 'Jaipur Dental College, Jaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Jodhpur Dental College General Hospital, Jodhpur', state: 'Rajasthan', type: 'Private' },
  { name: 'Maharaja Ganga Singh Dental College & Research Centre, Sri Ganganagar', state: 'Rajasthan', type: 'Private' },
  { name: 'Mahatma Gandhi Dental College & Hospital, Jaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'NIMS Dental College, Jaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Pacific Dental College & Research Centre', state: 'Rajasthan', type: 'Private' },
  { name: 'Pacific Dental College, Udaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'R.R. Dental College & Hospital, Udaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Rajasthan Dental College & Hospital, Jaipur', state: 'Rajasthan', type: 'Private' },
  { name: 'Surendera Dental College & Research Institute, Sri Ganganagar', state: 'Rajasthan', type: 'Private' },
  { name: 'Vyas Dental College & Hospital, Jodhpur', state: 'Rajasthan', type: 'Private' },
  // Tamil Nadu
  { name: 'Adhiparasakthi Dental College & Hospital, Melmaruvathur', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Asan Memorial Dental College & Hospital, Kancheepuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Best Dental Science College, Madurai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Chettinad Dental College & Research Institute, Kancheepuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'CSI College of Dental Sciences & Research, Madurai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Dhanalakshmi Srinivasan Dental College', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Government Dental College, Pudukkottai', state: 'Tamil Nadu', type: 'Govt' },
  { name: 'Govt. Dental College & Hospital, Cuddalore', state: 'Tamil Nadu', type: 'Govt' },
  { name: 'JKK Natrajah Dental College & Hospital, Komarapalayam', state: 'Tamil Nadu', type: 'Private' },
  { name: 'K.S.R. Institute of Dental Science & Research, Tiruchengode', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Karpaga Vinayaga Institute of Dental Sciences, Kanchipuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Madha Dental College & Hospital, Kundrathur', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Meenakshi Ammal Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Nandha Dental College and Hospital', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Priyadarshini Dental College & Hospital, Pandur', state: 'Tamil Nadu', type: 'Private' },
  { name: 'R.V.S. Dental College & Hospital, Sulur', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Ragas Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Rajas Dental College & Hospital, Kavalkinaru Jn', state: 'Tamil Nadu', type: 'Private' },
  { name: 'S.R.M. Dental College, Ramapuram, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sathyabama University Dental College and Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Saveetha Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sree Balaji Dental College & Hospital, Narayanpuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sree Mookambika Institute of Dental Sciences, Kulasekharam', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sri Ramachandra Dental College & Hospital, Porur', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sri Ramakrishna Dental College & Hospital, Coimbatore', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Sri Venkateswara Dental College & Hospital, Kancheepuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'SRM Kattankulathur Dental College & Hospital, Kanchipuram', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Tagore Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: 'Tamil Nadu Government Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Govt' },
  { name: 'Thai Moogambigai Dental College & Hospital, Chennai', state: 'Tamil Nadu', type: 'Private' },
  { name: "Vinayaka Mission's Sankarachariyar Dental College, Salem", state: 'Tamil Nadu', type: 'Private' },
  { name: 'Vivekanandha Dental College for Women, Elayampalayam', state: 'Tamil Nadu', type: 'Private' },
  // Telangana
  { name: 'Army College of Dental Sciences, Secunderabad', state: 'Telangana', type: 'Private' },
  { name: 'Government Dental College and Hospital, Hyderabad', state: 'Telangana', type: 'Govt' },
  { name: 'Kamineni Institute of Dental Sciences, Nalgonda', state: 'Telangana', type: 'Private' },
  { name: 'Malla Reddy Dental College for Women, Hyderabad', state: 'Telangana', type: 'Private' },
  { name: 'Malla Reddy Institute of Dental Sciences, Hyderabad', state: 'Telangana', type: 'Private' },
  { name: 'Mamata Dental College, Khamam', state: 'Telangana', type: 'Private' },
  { name: 'Mamata Institute of Dental Sciences', state: 'Telangana', type: 'Private' },
  { name: 'Meghna Institute of Dental Sciences, Nizamabad', state: 'Telangana', type: 'Private' },
  { name: 'MNR Dental College & Hospital, Medak', state: 'Telangana', type: 'Private' },
  { name: 'Panineeya Mahavidyalaya Institute of Dental Sciences & Research Centre, Hyderabad', state: 'Telangana', type: 'Private' },
  { name: 'Sri Balaji Dental College, Hyderabad', state: 'Telangana', type: 'Private' },
  { name: 'Sri Sai College of Dental Surgery, Vikarabad', state: 'Telangana', type: 'Private' },
  { name: 'Sri Venkata Sai Institute of Dental Sciences, Hyderabad', state: 'Telangana', type: 'Private' },
  { name: 'Tirumala Institute of Dental Sciences & Research Centre', state: 'Telangana', type: 'Private' },
  // Tripura
  { name: 'Agartala Government Dental College and IGM Hospital', state: 'Tripura', type: 'Govt' },
  // Uttar Pradesh
  { name: 'Babu Banarasi Das College of Dental Sciences, Lucknow', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Career Institute of Dental Sciences & Hospital, Lucknow', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Chandra Dental College & Hospital, Safedabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'D.J. College of Dental Sciences & Research, Modi Nagar', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Dental College Azamgarh', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Dr. Ziauddin Ahmad Dental College, Aligarh', state: 'Uttar Pradesh', type: 'Govt' },
  { name: 'Faculty of Dental Sciences, Banaras Hindu University, Varanasi', state: 'Uttar Pradesh', type: 'Govt' },
  { name: 'Faculty of Dental Sciences, Lucknow', state: 'Uttar Pradesh', type: 'Govt' },
  { name: 'I.T.S. Centre for Dental Studies & Research, Ghaziabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'I.T.S. Dental College, Hospital & Research Centre, Greater Noida', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Inderprastha Dental College & Hospital, Ghaziabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Institute of Dental Sciences, Bareilly', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Institute of Dental Studies & Technology, Modinagar', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'K.D. Dental College, Mathura', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Kalka Dental College & Hospital, Meerut', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Kothiwal Dental College & Research Centre, Moradabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Maharana Pratap Dental College & Hospital, Kanpur', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Purvanchal Institute of Dental Sciences, Gorakhpur', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Rama Dental College, Hospital & Research Centre, Kanpur', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Santosh Dental College & Hospital, Ghaziabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Saraswati Dental College, Lucknow', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Sardar Patel Post Graduate Institute of Dental & Medical Sciences, Lucknow', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'School of Dental Sciences, Greater Noida', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Shree Bankey Bihari Dental College & Research Centre, Masuri', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Subharati Dental College, Meerut', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'Teerthanker Mahaveer Dental College & Research Centre, Moradabad', state: 'Uttar Pradesh', type: 'Private' },
  { name: 'U.P. Rural Institute of Medical Sciences & Research, Saifai', state: 'Uttar Pradesh', type: 'Govt' },
  // Uttarakhand
  { name: 'Seema Dental College & Hospital, Rishikesh', state: 'Uttarakhand', type: 'Private' },
  { name: 'Uttaranchal Dental College & Medical Research Institute, Dehradun', state: 'Uttarakhand', type: 'Private' },
  // West Bengal
  { name: 'Burdwan Dental College, Rajbati', state: 'West Bengal', type: 'Govt' },
  { name: 'Dr. R. Ahmed Dental College & Hospital, Calcutta', state: 'West Bengal', type: 'Govt' },
  { name: 'Gurunanak Institute of Dental Science & Research, Kolkata', state: 'West Bengal', type: 'Private' },
  { name: 'Haldia Institute of Dental Sciences and Research, Banbishnupur', state: 'West Bengal', type: 'Private' },
  { name: 'Kusum Devi Sunderlal Dugar Jain Dental College & Hospital, Kolkata', state: 'West Bengal', type: 'Private' },
  { name: 'Sanaka Institute of Dental Sciences, Durgapur', state: 'West Bengal', type: 'Private' },
  { name: 'The North Bengal Dental College, Sushratangar', state: 'West Bengal', type: 'Govt' },
];
